### DISCUSSION TITLE
Load balancing to a backed websocket service using "least_conn"

### DISCUSSION THREAD

**Discussion by vkbodanki** [nginx/kubernetes-ingress#1960] [Q&A] [answered]
Hi, I am trying to set up the ingress controller to load balance to a websocket backed svc using the "least_conn" algorithm for load balancing.

To being with, I have a service that accepts incoming websocket connections for clients. Kubeproxy is currently responsible for load balancing the incoming websocket requests across different service pods. Everything works fine with round-robin algorithm that Kubeproxy supports.

Now I wanted to replace Kubeproxy with Nginx ingress controller for load balancing the websocket connections to my backend service pods. I configured all the moving parts necessary for Nginx and got websocket load balancing to work with Nginx ingress controller. However, I still see that the load balancing is still round-robin even though I configured the lb-method to "least_conn".  I am not sure if I missed a configuration that enables using different load balancing options. Any help is greatly appreciated.

Here is the Ingress config.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: mytest-ingress-nginx
 annotations:
  nginx.org/websocket-services: "mytest-svc"
  nginx.org/ssl-services: "mytest-svc"
  nginx.org/lb-method: "least_conn"
spec:
 ingressClassName: nginx
 tls:
 - hosts:
   - "testApp.westus2.cloudapp.azure.com"
   secretName: nginx-ingress-tls
 rules:
 - host: "testApp.westus2.cloudapp.azure.com"
   http:
    paths:
    - path: /direct
      pathType: Prefix
      backend:
       service:
        name: mytest-svc
        port:
         number: 10443
```
