### DISCUSSION TITLE
how to configure external DNS with NGINX and AWS loadbalancer (nlb)

### DISCUSSION THREAD

**Discussion by nahshal** [nginx/kubernetes-ingress#2246] [Q&A]
Hallo there, 
I have a problem configuring my nginx. Problem is following.
We have our DNS service that I can not change. let us see we have reserved the DNS  cloudservices.company.com.
This DNS will forwards all traffic to our aws NLB Loadbalancer through NGINX like following.

NLB: example12348695758575.elb.region.amazonaws.com

my ingress-rules.yaml is like 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-resources-name
  namespace: my-apps
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: example12348695758575.elb.region.amazonaws.com
    http:
      paths:
        - path: /tee
          backend:
            serviceName: tee-service
            servicePort: 8080
        - path: /coffee
          backend:
            serviceName: coffee-service
            servicePort: 8080
```

My config.yaml currently looks like 

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.14
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
```

my question is:
when I call now the nlb direct, it works and I can see my services. But if I use the DNS then I got errors like 

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.0.14
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
allow-snippet-annotations: 'true'
  http-snippet: |
    server {
      listen 80;
      server_name   cloudservices.company.com;
     }
  use-forwarded-headers: 'true'
```

I got the error

```
W1207 09:45:54.777377       8 controller.go:829] Error obtaining Endpoints for Service "my-apps/ks-console": no object matching key "my-apps/ks-console" in local store
2021/12/07 09:45:55 [error] 13410#13410: *5998387 open() "/usr/local/nginx/html/tee/getVersion" failed (2: No such file or directory), client: 149.219.220.108, server: cloudservices.wdr.de, request: "GET /tee/getVersion HTTP/1.1", host: "cloudservices.company.com"
149.219.220.108 - - [07/Dec/2021:09:45:55 +0000] "GET /tee/getVersion HTTP/1.1" 404 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36" 855 0.000 [] [] - - - - 8c52b4b09ed44ce028f44fc30085dddd
```

what should I add to the config or how to reconfigure my nginx to forwards the traffic coming from our DNS to our NLB through NGINX.
