### DISCUSSION TITLE
server-alias annotation to allow multiple hosts for the same ingress?

### DISCUSSION THREAD

**Discussion by hostalp** [nginx/kubernetes-ingress#2405] [Ideas]
Hello,
is there any functionality similar to what's provided by the other ingress controller via the annotation [nginx.ingress.kubernetes.io/server-alias](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#server-alias)?
> Allows the definition of one or more aliases in the server definition of the NGINX configuration using the annotation nginx.ingress.kubernetes.io/server-alias: "<alias 1>,<alias 2>". This will create a server with the same configuration, but adding new values to the server_name directive.

It's an easy way how to add multiple hosts to the configuration.
I searched the documentation a little, but haven't found anything so I have to use the alternative approach with YAML anchors to reuse the same http configuration section by multiple hosts.
It would be nice to have this feature available though.

**Comment by brianehlert** [comment]
The use case is that you want to define a list of hostnames instead of being constrained to a single hostname for an Ingress or a VirtualServer.
This implies that these hostnames then all have an identical configuration including the backend.

An example that immediately jumps to mind is external.dns.name and internal.dns.name to align with the behavior that NGINX does hostname validation by default.

Does that align with the thinking?  Do you have a different example?

**Reply by hostalp** [reply]
Another example is the use of `www.dns.name` and `dns.name` in a single ingress resource.

**Comment by brianehlert** [comment]
Any alias would be appended after the hostname.
The existing host would be configured in nginx.conf as the server_name with any aliases following.

See:

- https://serverfault.com/questions/718801/server-aliases-on-nginx
- https://nginx.org/en/docs/http/server_names.html

It would be relatively straightforward to use an alias annotation that post-pends after the canonical host name given in the main body of the configuration.

I am guessing that the historic reason for not adding this is that hostname collisions could happen.  Today that is resolved by using the oldest object wins methodology.  But it could be possible to introduce an alias on one ingress object that clashes with an alias defined on another.
The question becomes: how this is resolved or not resolved and reported.

In the case of a business merge or similar, I could see an alias quickly being some alternative DNS name.

I am also curious how this might relate to projects such as external-dns or loadbalancers.  Or if in those cases it is not worried about.
_Asking since I don't know_

**Comment by vepatel** [comment]
For both Ingress and VirtualServer

**Comment by shaun-nx** [comment]
For VirtualServer, would this be a new spec block or will the existing `spec.host` field become a list?

For example:
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  hosts:
    - host: cafe.example.com
    - host: foo.example.com
```

**Reply by brianehlert** [reply]
To have a canonical primary a way to approach this would probably be to be explicit about alias rather than array or host names.
I say that because an alias pattern would be used different by the customer than I think a list of hosts would.
Alias implies that the domain would be the same.  Which I feel is highly appropriate.  An array of host names implies randomness.
Consider this pattern:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  hosts:
    - host: example.com
    - alias: www.example.com
    - alias: example.net
    - alias: www.example.net
```

In the nginx.conf this would translate to:

```
server {
    listen       80;
    server_name  example.com  www.example.com example.net www.example.net;
    ...
}
```

YAML syntax might need to be updated a bit if VirtualServer supports an array of host names.  In which case consider this:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  hosts:
    - host: example.com
       alias: www.example.com
       alias: example.net
       alias: www.example.net
    - host: contoso.com
      alias: www.contoso.com
```
