### DISCUSSION TITLE
How can I define a `limit_req_zone`?

### DISCUSSION THREAD

**Discussion by juanpabloaj** [nginx/kubernetes-ingress#2564] [Q&A] [answered]
I have this ingress file

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-test"
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.org/location-snippets: |
      limit_req zone=by_web;
spec:
  ingressClassName: nginx
  rules:
    - host: my.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80
  tls:
    - hosts:
        - my.domain.com
      secretName: quickstart-example-tls
```

I was able to define a `limit_req` using `nginx.org/location-snippets`.

How can I define the `limit_req_zone`?

```
limit_req_zone $request_uri zone=by_web:10m rate=60r/m;
```

Regards.
