### DISCUSSION TITLE
How can i apply the split_client module in a kubernetes-ingress?

### DISCUSSION THREAD

**Discussion by jeffny2015** [nginx/kubernetes-ingress#2607] [Q&A] [answered]
How can i apply the split_client module in a kubernetes-ingress?

something like this: https://www.nginx.com/blog/sampling-requests-with-nginx-conditional-logging/
but in a kubernetes ingress

**Comment by jasonwilliams14** [comment]
@jeffny2015 Hello.
You have two options.

if you use our CRDs, you can use the builtin `split` capability that you can see documented here:

https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#split

If you continue to use `ingress` resource, then you would need to use snippets to setup `split` for your resource.

HTH

**Reply by jovankricka** [reply]
I need to do something similar and attempted to use the `split_clients` directive in the snippets section .
However I keep getting this:

> nginx: [emerg] "split_clients" directive is not allowed here in /tmp/nginx-cfg3510962041:924

Do you have any idea how to use split_clients directive in nginx k8s config?

**Reply by jasonwilliams14** [reply, marked as answer]
@jovankricka 
Here is a simple example of using `split` with our `virtualServer` CRD:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee-v1
    service: coffee-v1-svc
    port: 80
  - name: coffee-v2
    service: coffee-v2-svc
    port: 80
  routes:
  - path: /coffee
    splits:
    - weight: 90
      action:
        pass: coffee-v1
    - weight: 10
      action:
        pass: coffee-v2
```
