### DISCUSSION TITLE
Issue with externalname

### DISCUSSION THREAD

**Discussion by whitakersp-fineos** [nginx/kubernetes-ingress#2769] [Q&A]
Hey. there, i'm trying to setup an ingress for an external url and I'm following the very light instructions here, https://github.com/nginxinc/kubernetes-ingress/tree/v2.2.2/examples/externalname-services.

Here's my setup.

```
kind: Service
apiVersion: v1
metadata:
  name: test-external-url
spec:
  type: ExternalName
  externalName: static.wikia.nocookie.net
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-ingress
spec:
  rules:
  - host: $(INGRESS_HOST)  
    http:
      paths:
      - path: /wikia
        pathType: Prefix
        backend:
          service:
            name: test-external-url
            port:
              number: 80
```

I added the `resolver-address` to my configmap and set that to the cluster-ip of kube-dns.

Problem is when I look at the `/etc/nginx/conf.d/generetedfile.conf` I see my location route and the upstream it created, but the up stream is missing any kind of server information for what i'm proxying, and i get a 502 error and the logs of course say no live upstreams found. 

Here's what is generated

```
upstream eng-dev-sandbox-external-eip-eng-dev-sandbox.testsite-eng.com-test-external-url-80 {
        zone eng-dev-sandbox-external-eip-eng-dev-sandbox.testsite-eng.com-test-external-url-80 512k;
        random two least_conn;
}
```

Any idea what i'm doing wrong here?
