### DISCUSSION TITLE
Install nginx ingress on EKS with private LB

### DISCUSSION THREAD

**Discussion by gkumarchilakala** [nginx/kubernetes-ingress#2875] [General]
Hi Community Members,

Can you help me with the exact command to install nginx ingress controller on AWS EKS 1.22 using the helm command.

I don't require the custom resources and appprotect
and create internal only Load balancer with annoatation: service.beta.kubernetes.io/aws-load-balancer-internal: "true"

I came up with this command, is it correct?

helm install my-release nginx-stable/nginx-ingress --set controller.enableCustomResources=false --set controller.appprotect.enable=false --set controller.service.external.enabled=false --set controller.service.internal.enabled=true --set controller.service.internal.annotations.service.beta.kubernetes.io/aws-load-balancer-internal: "true"

**Comment by vitorfhc** [comment]
I am not sure if this is going to help you, but here are the `values.yaml` I used to deploy it using a private NLB.

```yaml
ingress-nginx:
  controller:
    ingressClassResource:
      default: false

    service:
      external:
        enabled: false

      internal:
        enabled: true
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

**Reply by gkumarchilakala** [reply]
Thanks Victor, these are the options i was looking for.
I would go ahead and test using the above values

**Reply by vitorfhc** [reply]
As you can see, there are some duplicated annotations:

```yaml
service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

I think EKS doesn't know how to deal with the new ones, so I also needed to add deprecated annotations. It's worth mentioning that I am using 1.21 clusters, which may be one reason.

**Comment by babinos87** [comment]
Do those values.yaml work for `nginxinc/kubernetes-ingress` (this github repository)? I think those are for [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) module? I don't see any reference neither to `controller.service.external` nor to `controller.service.internal` here: https://github.com/nginxinc/kubernetes-ingress/blob/main/charts/nginx-ingress/values.yaml#L319.

I tried the suggestion nevertheless and it didn't work - I still got an external ELB.

I know that those work for `kubernetes/ingress-nginx` because I've used them, but this helm chart seems it's different. Are you aware of any solution / suggestion for this helm chart / git repo?

**Reply by babinos87** [reply]
That's what worked for me when using `nginxinc/kubernetes-ingress` module:

```
controller:
    service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          # other stuff
          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-xxxxx
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:xxxxxx:certificate/cert-id"
```
