### DISCUSSION TITLE
How to support http and https in the application-level?

### DISCUSSION THREAD

**Discussion by icefery** [nginx/kubernetes-ingress#2949] [Q&A]
## Waht I Expected

I am using http and https in the application-level, and then I just want to use "virtual host" in the ingress-level.

## Application Level Code

```js
const http = require('http')
const https = require('https')
const fs = require('fs')
const path = require('path')
const express = require('express')

const app = express()

app.get('/*', (req, res) => res.json({ url: `${req.protocol}://${req.get('host')}${req.originalUrl}` }))

const httpPort = 8080
http.createServer(app).listen(httpPort, () => console.log(`Listening on :${httpPort}`))

const httpsPort = 8443
const options = {
  key: fs.readFileSync(path.join(__dirname, './certs/domain.key')),
  cert: fs.readFileSync(path.join(__dirname, './certs/domain.crt'))
}
https.createServer(options, app).listen(httpsPort, () => console.log(`Listening on :${httpsPort}`))
```

Now when I execute `curl http://127.0.0.1:8080` then it responses `{"url":"http://127.0.0.1:8080/"}`, when I execute `curl -k https://127.0.0.1:8443` then it reponses `{"url":"https://127.0.0.1:8443/"}`.

## Ingress Level Config

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  type: ClusterIP
  ports:
    - { name: http, port: 8080, protocol: TCP, targetPort: 8080 }
    - { name: https, port: 8443, protocol: TCP, targetPort: 8443 }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  labels:
    app: my-app
spec:
  ingressClassName: nginx
  rules:
    - host: my-app.dev.icefery.xyz
      http:
        paths:
          - backend:
              service:
                name: my-app
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - my-app.dev.icefery.xyz
```

Now when I execute `curl http://my-app.dev.icefery.xyz` or `curl -k https://my-app.dev.icefery.xyz` then it just responses `{"url":"http://my-app.dev.icefery.xyz/"}`, which means my ingress configuration only uses the port specified(either http or https), and can not support http and https configed in the application-levle.

## Question

How could I use "virtual host" in the ingress-level to support http and https configed in the application-level?

Thanks!
