### DISCUSSION TITLE
VirtualServer + Cert-manager with enabled mtls

### DISCUSSION THREAD

**Discussion by alexandersm** [nginx/kubernetes-ingress#3145] [General]
Hello, 

I think , this topic has not been described before 

I've configured VritualServer with CertManager to use Let's encrypt certificates, everything works fine. 

On top of this configuration, I would like to enable mTLS configuration with the self-signed certificate also issued by cert-manager.

Cert-manager has created the secret with the name **certsecret**, but it can not be used in the Nginx Ingress Policy object, because **certsecret** has type "kubernetes.io/tls", whereas Nginx Ingress requires the type "nginx.org/ca"

What would be a workaround here?

My Policy object:

```
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: ingress-mtls-policy
spec:
  ingressMTLS:
    clientCertSecret: certsecret
    verifyClient: "on"
    verifyDepth: 1
```

Kind regards, 
Alexander.
