### DISCUSSION TITLE
Exposing CoAP Service with IP preservation

### DISCUSSION THREAD

**Discussion by StevenCyb** [nginx/kubernetes-ingress#3554] [Q&A]
Hi,

since I didn't really have an idea after a few hours, I just wanted to ask for some advice. I have a CoAP server running in AWS EKS. So far everything works with the `transportserver` pointing at my service. Now I have the requirement that I need the client IP. By default, the IP of the Nginx pod is passed.

I use helm to deploy the Nginx controller.

One idea I had was to add `serverSnippets: proxy_bind $remote_addr transparent;` to the transportserver and modifying the daemonset to get more permissions:
```
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 101 #nginx
          runAsNonRoot: true
          privileged: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
            - NET_ADMIN
            - NET_RAW
            - CAP_NET_ADMIN
```
But still getting the error:
```
[alert] 155#155: *13120 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, udp client: <IP_I_WANT>, server: 0.0.0.0:8000, upstream: "<IP_I_GET>:8000", bytes from/to client:61/0, bytes from/to upstream:0/0
```

Another idea was to implement a lua plugin that can add the client IP as CoAP option. The problem ist, I can't find any hints on how to include plugins e.g. by mounting them to a specific directory in combination with the helm chart.

Do someone have a idea or hint on how to achieve it?
