### DISCUSSION TITLE
does not have any active Endpoint.

### DISCUSSION THREAD

**Discussion by taqihrizvi** [nginx/kubernetes-ingress#3633] [Q&A] [answered]
I am getting this error when i upgraded my Kubernetes version on my AKS cluster 

NGINX Ingress controller
  Release:       v1.4.0
  Build:         50be2bf95fd1ef480420e2aa1d6c5c7c138c95ea
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.10

-------------------------------------------------------------------------------

W0310 11:50:56.507021       7 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0310 11:50:56.507154       7 main.go:209] "Creating API client" host="https://10.0.0.1:443"
I0310 11:50:56.543039       7 main.go:253] "Running in Kubernetes cluster" major="1" minor="24" git="v1.24.9" state="clean" commit="57fbbcc2804848b95cad5519f5
ec9d6355430db9" platform="linux/amd64"
I0310 11:50:56.756763       7 main.go:104] "SSL fake certificate created" file="/etc/ingress-controller/ssl/default-fake-certificate.pem"
I0310 11:50:56.775362       7 ssl.go:533] "loading tls certificate" path="/usr/local/certificates/cert" key="/usr/local/certificates/key"
I0310 11:50:56.795074       7 nginx.go:260] "Starting NGINX Ingress controller"
I0310 11:50:56.811865       7 event.go:285] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"ingress-basic", Name:"nginx-ingress-ingress-nginx-controller
", UID:"5757472d-67e9-4f82-a58c-caec0f58f851", APIVersion:"v1", ResourceVersion:"22152023", FieldPath:""}): type: 'Normal' reason: 'CREATE' ConfigMap ingress-
basic/nginx-ingress-ingress-nginx-controller
I0310 11:50:57.900366       7 store.go:430] "Found valid IngressClass" ingress="develop/develop-unified-ingress" ingressclass="nginx"
I0310 11:50:57.901578       7 event.go:285] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"develop", Name:"develop-unified-ingress", UID:"d0c1fb93-80e2-4
8e3-b4ed-5c58af2c28d6", APIVersion:"networking.k8s.io/v1", ResourceVersion:"24658494", FieldPath:""}): type: 'Normal' reason: 'Sync' Scheduled for sync
I0310 11:50:57.996676       7 nginx.go:303] "Starting NGINX process"
I0310 11:50:57.996774       7 leaderelection.go:248] attempting to acquire leader lease ingress-basic/ingress-controller-leader...
I0310 11:50:57.997141       7 nginx.go:323] "Starting validation webhook" address=":8443" certPath="/usr/local/certificates/cert" keyPath="/usr/local/certific
ates/key"
W0310 11:50:57.997577       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:50:57.997672       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
I0310 11:50:57.997798       7 controller.go:168] "Configuration changes detected, backend reload required"
I0310 11:50:58.002004       7 status.go:84] "New leader elected" identity="nginx-ingress-ingress-nginx-controller-6647c7779d-lpwkb"
I0310 11:50:58.093407       7 controller.go:185] "Backend successfully reloaded"
I0310 11:50:58.093536       7 controller.go:196] "Initial sync, sleeping for 1 second"
I0310 11:50:58.093591       7 event.go:285] Event(v1.ObjectReference{Kind:"Pod", Namespace:"ingress-basic", Name:"nginx-ingress-ingress-nginx-controller-6647c
7779d-xck99", UID:"d7246654-6d98-451f-a992-fa84789cf800", APIVersion:"v1", ResourceVersion:"24659659", FieldPath:""}): type: 'Normal' reason: 'RELOAD' NGINX r
eload triggered due to a change in configuration
W0310 11:51:01.800889       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:01.801014       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:05.134430       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:05.134554       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:08.467755       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:08.468026       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:11.801926       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:11.802148       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:15.134454       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:15.134577       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:20.148933       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:20.149161       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:23.483068       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:23.483204       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:26.816003       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:26.816110       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:32.112999       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:32.113539       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:35.447164       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:35.447321       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:38.779811       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:38.779938       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:42.113117       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:42.113283       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:51:45.446465       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:51:45.446681       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
I0310 11:52:15.553617       7 status.go:84] "New leader elected" identity="nginx-ingress-ingress-nginx-controller-6647c7779d-6z2w4"
W0310 11:53:40.326607       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.
W0310 11:53:47.320393       7 controller.go:1112] Service "develop/camera-service" does not have any active Endpoint.
W0310 11:53:47.320499       7 controller.go:1112] Service "develop/sp-platform" does not have any active Endpoint.

```
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: develop
  name: develop-unified-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/request-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    er-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "Upgrade";
        proxy_cache_bypass $http_upgrade;
        }
spec:
  rules:
    - host: devgateway.com
      http:
        paths:
          - backend:
              service:
                name: adminer-dev
                port:
                  number: 8080
            path: /adminer.php(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: fms-fleet
                port:
                  number: 8010
            path: /fms-fleet/(.*)
            pathType: Prefix
          - backend:
              service:
                name: fms-driver
                port:
                  number: 8011
            path: /fms-driver/(.*)
            pathType: Prefix
          - backend:
              service:
                name: fms-maintenance
                port:
                  number: 8012
            path: /fms-maintenance/(.*)
            pathType: Prefix
          - backend:
              service:
                name: user-ms
                port:
                  number: 8013
            path: /user-ms/(.*)
            pathType: Prefix
          - backend:
              service:
                name: cob-packages
                port:
                  number: 8021
            path: /cob-packages/(.*)
            pathType: Prefix
          - backend:
              service:
                name: cob-customer
                port:
                  number: 8022
            path: /cob-customer/(.*)
            pathType: Prefix
          - backend:
              service:
                name: cob-inventory
                port:
                  number: 8023
            path: /cob-inventory/(.*)
            pathType: Prefix
          - backend:
              service:
                name: cob-new-customer
                port:
                  number: 8024
            path: /cob-new-customer/(.*)
            pathType: Prefix
          - backend:
              service:
                name: maptrail-generic
                port:
                  number: 8031
            path: /maptrail-generic/(.*)
            pathType: Prefix
          - backend:
              service:
                name: map-trail
                port:
                  number: 8032
            path: /map-trail/(.*)
            pathType: Prefix
          - backend:
              service:
                name: smpp-mail
                port:
                  number: 8033
            path: /smpp-mail/(.*)
            pathType: Prefix
          - backend:
              service:
                name: jubaili-be
                port:
                  number: 8035
            path: /jubaili-be/(.*)
            pathType: Prefix
          - backend:
              service:
                name: at-advance
                port:
                  number: 8036
            path: /at-advance/(.*)
            pathType: Prefix
          - backend:
              service:
                name: loki
                port:
                  number: 3100
            path: /loki/(.*)
            pathType: Prefix
          - backend:
              service:
                name: camera-service
                port:
                  number: 8037
            path: /camera-service/(.*)
            pathType: Prefix
          - backend:
              service:
                name: report-analytics
                port:
                  number: 8038
            path: /report-analytics/(.*)
            pathType: Prefix
          - backend:
              service:
                name: scheduler-ms
                port:
                  number: 8039
            path: /scheduler-ms/(.*)
            pathType: Prefix
          - backend:
              service:
                name: platform-audit
                port:
                  number: 8040
            path: /platform-audit/(.*)
            pathType: Prefix
          - backend:
              service:
                name: device-manager
                port:
                  number: 8041
            path: /device-manager/(.*)
            pathType: Prefix
          - backend:
              service:
                name: platform-role-access
                port:
                  number: 8042
            path: /platform-role-access/(.*)
            pathType: Prefix
          - backend:
              service:
                name: notification-alerts
                port:
                  number: 8043
            path: /notification-alerts/(.*)
            pathType: Prefix
          - backend:
              service:
                name: smart-building
                port:
                  number: 8044
            path: /smart-building/(.*)
            pathType: Prefix
          - backend:
              service:
                name: live-stream
                port:
                  number: 5000
            path: /live-stream/(.*)
            pathType: Prefix
          - backend:
              service:
                name: live-stream
                port:
                  number: 4400
            path: /ws-live-stream/(.*)
            pathType: Prefix
          - backend:
              service:
                name: sp-platform
                port:
                  number: 8087
            path: /sp-platform/(.*)
            pathType: Prefix`
```
            
          My ingress file looks like this it was working fine before the upgrade.
