### DISCUSSION TITLE
Ingress - rewrite url and pass base tag

### DISCUSSION THREAD

**Discussion by dkirrane** [nginx/kubernetes-ingress#3707] [Q&A] [answered]
What is the equivalent of the community annotations?
```
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
```

I have tried the following but think it's only half the solution.
I think I need a furthur annotation that will prepend a base tag in the header of the returned HTML from the backend to fix relative links.
```
nginx.org/rewrites: serviceName=my-dashboard rewrite=/
```

My Ingress Resource 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard
  namespace: default
  labels:
    app: dashboard
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - foo.company.com
      secretName: cert-tls
  rules:
    - host: foo.avaya.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-dashboard
                port:
                  number: 80
```
