### DISCUSSION TITLE
Blankscreen / Service won't load

### DISCUSSION THREAD

**Discussion by RFlintstone** [nginx/kubernetes-ingress#3716] [Q&A]
[Creating new post because the post I found is relatively dated]

I'm currently using Cloudflare Tunnel for secure connections with my domain(s) but the Nginx Controller doesn't like the SSL certificate. Now I am as far that I'm getting a blank page most likely because Nginx is unable to check the certificate. (With the Cloudflare ingress it does work so it isn't Cloudflared - switched to Nginx because Cloudflare ingress's `/paths` don't work (well)

Although I rather have a certificate, I just found [this](https://github.com/nginxinc/kubernetes-ingress/issues/925#issuecomment-616377783) post with a potential solution, but I can't seem to find the way to configure it. Does someone know how to solve this? Is that solution even still compatible with the last released chart, `nginx-ingress-0.17.0`?

This is the output of svc:
```
NAME                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kuard                 ClusterIP   10.97.18.82      <none>        80/TCP    70m
kubernetes            ClusterIP   10.96.0.1        <none>        443/TCP   27h
kubernetes-bootcamp   ClusterIP   10.107.5.7       <none>        80/TCP    12h
web-service           ClusterIP   10.104.129.217   <none>        80/TCP    14h
```

This is the output of deploy:
```
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
cloudflared           2/2     2            2           53m
httpbin-deployment    2/2     2            2           14h
kuard                 1/1     1            1           71m
kubernetes-bootcamp   1/1     1            1           12h
```

This is my current ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-ingress
  annotations:
    #kubernetes.io/ingress.class: nginx
    #nginx.org/ssl-passthrough: "true"
    #nginx.org/backend-protocol: "HTTPS"
    #nginx.org/rewrite-target: /
    nginx.org/server-snippets: |
      proxy_ssl_verify off;
spec:
  ingressClassName: nginx
  #tls:
  #- hosts:
  #  - projectsincluded.net
  #  secretName: pi-secret
  rules:
  - host: projectsincluded.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: kubernetes-bootcamp
            port:
              number: 80
```
