### DISCUSSION TITLE
Ingress cannot find the my app

### DISCUSSION THREAD

**Discussion by vahidazad** [nginx/kubernetes-ingress#3729] [Q&A] [answered]
Hi
I am new to Kubernetes.

my setup:
- nginx deployment as an app
- nginx service
- nginx ingress controller
- myapp ingress rule

**deployment:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

**nginx service**
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
```

**My app Ingress**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: nginx-service
            port:
              number: 8080
```

**Services:**
```
k get svc
NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.106.160.11    <pending>     80:32189/TCP,443:31960/TCP   30h
ingress-nginx-controller-admission   ClusterIP      10.97.119.19     <none>        443/TCP                      30h
kubernetes                           ClusterIP      10.96.0.1        <none>        443/TCP                      2d21h
nginx-service                        ClusterIP      10.105.137.251   <none>        8080/TCP                     21m
```

**ingress**
```
k get ingress
NAME            CLASS    HOSTS         ADDRESS   PORTS   AGE
myapp-ingress   <none>   example.com             80      30m
```

**Pods**
```
k get pods
NAME                                        READY   STATUS    RESTARTS        AGE
ingress-nginx-controller-5c6fd54c59-t5k6f   1/1     Running   1 (8m32s ago)   30h
nginx-deployment-7f456874f4-6hhqh           1/1     Running   1 (6m54s ago)   2d7h
```

I configured "example.com" internally on my pc pointing to the worker node IP of my cluster.
```
ping example.com

Pinging example.com [192.168.0.8] with 32 bytes of data:
Reply from 192.168.0.8: bytes=32 time=4ms TTL=64
Reply from 192.168.0.8: bytes=32 time=3ms TTL=64
Reply from 192.168.0.8: bytes=32 time=4ms TTL=64
```

But I don't get any response when using the domain name in the URL. any help is appreciated.

However, I get a "Welcome to nginx!" when I use the NodePort directly: http://example.com:30000/

`nginx-service                        NodePort       10.105.137.251   <none>        8080:30000/TCP               26m`
