### DISCUSSION TITLE
Forward OIDC id_token to backends

### DISCUSSION THREAD

**Discussion by brianehlert** [nginx/kubernetes-ingress#3767] [Ideas]
Enhance the OIDC Policy object to include the option to forward the ID token to the backend.
This would result in two token forwarding options: one for the access token (existing) and one for the ID token.

The proposal for the Policy change would look like this:

```
spec:
  oidc:
    clientID: nginx-plus
    clientSecret: oidc-secret
    authEndpoint: https://idp.example.com/openid-connect/auth
    tokenEndpoint: https://idp.example.com/openid-connect/token
    jwksURI: https://idp.example.com/openid-connect/certs
    accessTokenEnable: true
    idTokenEnable: true
```

This is implemented using the [OIDC reference implementation ](https://github.com/nginxinc/nginx-openid-connect/) and involves saving the oidc_id_token and adding it to the headers for the backend servers to intercept.

Similar to the PR that enabled access token: https://github.com/nginxinc/kubernetes-ingress/pull/3474

What needs to be forwarded appears to be the $session_jwt from here: https://github.com/nginxinc/nginx-openid-connect/blob/74948ce512e199ca6189fe75bbb2b52fcdbd0148/openid_connect_configuration.conf#L95
