### DISCUSSION TITLE
Deployment failed to create pod

### DISCUSSION THREAD

**Discussion by Nihilism0** [nginx/kubernetes-ingress#3806] [Q&A]
I want to deploy the ingress controller, but I don't know where there is a problem with my configuration file

```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: freecar-ink

spec:
  controller: nginx.org/ingress-controller

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freecar-ing

spec:
  ingressClassName: freecar-ink

  rules:
    - host: freecar.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: consul
                port:
                  number: 8500
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysql
                port:
                  number: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freecar-kic-dep
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freecar-kic-dep
  template:
    metadata:
      labels:
        app: freecar-kic-dep
    spec:
      serviceAccountName: nginx-ingress
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nginx-ingress
          image: nginx/nginx-ingress:2.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: readiness-port
              containerPort: 8081
            - name: prometheus
              containerPort: 9113
          readinessProbe:
            httpGet:
              path: /nginx-ready
              port: readiness-port
            periodSeconds: 1
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 101
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - -ingress-class=freecar-ink
            - -health-status
            - -ready-status
            - -nginx-status
            - -enable-snippets
            - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
            - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
---
apiVersion: v1
kind: Service
metadata:
  name: freecar-kic-svc
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: freecar-kic-dep
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
```
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/114405451/233825706-ca087065-1fc4-4e14-9853-efb33df47834.png">
Who can help me? This problem has been bothering me for a long time. Thank you very much
