### DISCUSSION TITLE
Make it easier to "attach" a VirtualServerRoute to a VirtualServer without requiring that the VirtualServer be modified

### DISCUSSION THREAD

**Discussion by brianehlert** [nginx/kubernetes-ingress#4092] [Ideas]
There are many customers that like the master-minion patter of the Ingress Resource.
Specifically the ability to define the Master that represents the hostname and core attributes such as TLS and then allow Minions to be defined that modify the behavior of that hostname by defining paths or other behavior modifiers.
This is also called "mergeable ingress".

Four years ago this project introduced its CRDs as an answer to problems that customers had identified with the Ingress resource, specifically the ability to provide safety guarantees around different portions to the configuration.  The K8s RBAC allowed an easy way to secure the different objects as a way to provide that safety.

One point of feedback that has come back repeatedly is that the similarity of the VirtualServer and VirtualServerRoute pattern, while powerful, does not offer the simplicity of the mergeable ingress pattern.
The limitation being that a VirtualServerRoute cannot simply and easily extend a VirtualServer object.

The core problem being that the VirtualServer object must be modified whenever a VirtualServerRoute is added.  Thus creating both a two step process that is difficult to automate, but also requiring that the person that adds the VSR also have access to the VS (thus breaking the safety boundary) or that two people in different groups have to orchestrate change with each other.

The end result is that it creates a core piece of friction that limits adoption of the VirtualServer/VirtualServerRoute and related CRD objects - which have already proven themselves more powerful and capable than Ingress with its mergeable and annotation pattern.

I am starting this discussion to explore ideas around how we can address this friction point between VS and VSR and still meet the core intention of creating an RBAC boundary and separation of responsibility that promotes configuration safety for those customers that continue to need that.

**Comment by brianehlert** [comment]
One idea that I had from looking at Gateway API and the pattern of RefernceGrant is that in the VirtualServer, instead of referencing descrete VirtualServerRoutes, would it work if rather a namespace or label were defined.

The intention of using a namespace or label is two fold:

- form an implicit trust with some 'folder' that can be secured
- have a way to inform a watcher that can then monitor that namespace / label for new VirtualServerRoute objects
- automatically attempt to merge those objects into the VirtualServer configuration block of NGINX

**Reply by pleshakov** [reply]
I would separate ReferenceGrant feature from the problem of selecting which VirtualServerRoute, because it is an additional security feature, rather than a mechanism to define which VSR to select. In fact, we can add ReferenceGrants right now, so it works with existing VS->VSR explicit selection feature, to allow users to prevent their VSRs included into a VS from a namespace they don't trust.

**Reply by brianehlert** [reply]
ReferenceGrant was suggested as a concept, since as you articulate, this is about making a relationship.
Adding paths without continually modifying the hostname.  The flexibility of Ingress master-minion, but with some controls.

**Comment by pleshakov** [comment]
Here is one possible approach.

Instead of explicitly configuring VSRs by namespace/name in a VSR, introduce a VSR selector, something similar to Gateway API https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1.RouteNamespaces 

### Example

#### Before

taken from https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/custom-resources/cross-namespace-configuration

VS:
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
  namespace: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  routes:
  - path: /tea
    route: tea/tea
  - path: /coffee
    route: coffee/coffee
```

Tea VSR
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: tea
  namespace: tea
spec:
  host: cafe.example.com
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  subroutes:
  - path: /tea
    action:
      pass: tea
```

Coffee VSR:
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: coffee
  namespace: coffee
spec:
  host: cafe.example.com
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  subroutes:
  - path: /coffee
    action:
      pass: coffee
```

In this example, if a user needs to add another VSR with path `/juice`, it will be necessary to modify the VS to add the corresponding path with the explicit route reference.

#### New approach

VS:
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
  namespace: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  routes:
  - path: /
     routeSelector: # select VSRs from all namespaces with the label app: cafe
        namespaces: 
          from: Selector
          selector:
            matchLabels:
             app: cafe
```

Tea VSR - same

Coffee VSR - same

In this example, if a user needs to add another VSR with path `/juice`, no modifications will be necessary to the VS, as long as the VSR namespace is included in the corresponding selector in the VS.

### More details

#### Personas

Same as before:
* Admin is responsible for defining a VS.
* Users are responsible for VSRs

#### How does a VSR get attached to a VS

For a VSR to get attached to a VS, the following needs to happen:
- The VS must include a selector that will select that VSR
- The VSR must has the same hostname as the VSR
- The VSR must have the same ingressClassName as the VS, so that the correct IngressController picks the VSR 

Note: a VSR will only get attached to a single VS as before. This is ensured by the fact that Ingress Controller only allows one VS per hostname.

#### Conflicts

Ingress Controller will need to resolve conflicts, because two VSRs might define conflicting rules. For example:
VSR 1
```yaml
  - path: /path
    action:
      pass: app-1
```
VSR 2
```yaml
  - path: /path
    action:
      pass: app-2
```

The Ingress Controller will handle those conflicts by selecting a winning rule.

#### Status Information

- Extend status of the VS so that includes how many VSRs it has picked up
- Extend status of the  VSR so that includes information if some or all of its routing rules were ignored because they conflict with the another VSR rules.
