### DISCUSSION TITLE
Transport Server from Rabbitmq on Openshift, connection refused

### DISCUSSION THREAD

**Discussion by andrescolodrero** [nginx/kubernetes-ingress#4138] [General]
Hi, 
I recently deployed the ingress operator in Openshift and im trying to access an instance of Rabbitmq out the cluster,
For testing, HTTP ingress work correct, but im trying to setuip tcp access.

But i cant make transportServer to work with rabbitmq.
 To reproduce:
1. Install Rabbitmq on rabbitmq-system namespace
2. Install a INgress controller with the operator on rabbitmq-system
3.  Expose rabbitmq services "rabbitmq-sandbox2" on port 5672
```
kind: Service
apiVersion: v1
metadata:
  annotations:
    rabbitmq.com/topology-allowed-namespaces: rabbitmq-system
  resourceVersion: '74006948'
  name: rabbitmq-sandbox2
  namespace: rabbitmq-system
  ownerReferences:
    - apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      name: rabbitmq-sandbox2
      uid: d74ea3d0-4f06-40a2-9157-4bc7fc9352a5
      controller: true
      blockOwnerDeletion: true
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmq-sandbox2
    app.kubernetes.io/part-of: rabbitmq
spec:
  ports:
    - name: amqp
      protocol: TCP
      appProtocol: amqp
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      appProtocol: http
      port: 15672
      targetPort: 15672
    - name: stream
      protocol: TCP
      appProtocol: rabbitmq.com/stream
      port: 5552
      targetPort: 5552
    - name: prometheus
      protocol: TCP
      appProtocol: prometheus.io/metrics
      port: 15692
      targetPort: 15692
  type: ClusterIP

  selector:
    app.kubernetes.io/name: rabbitmq-sandbox2
```
4. Create global configuration and create listener opn por "30552"

 `apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration 
metadata:
  name: nginx-configuration
  namespace: rabbitmq-system
spec: 
  listeners:
  - name: rabbitmq-tcp
    port: 30552
    protocol: TCP`

6. Create a transport server
`apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: rabbitmq-listener
  namespace: rabbitmq-system
spec:
  host: rabbitmq.apps.ocptest.domain.com
  listener:
    name: rabbitmq-tcp
    protocol: TCP
upstreams:
- name: rabbitmq-sandbox2
  service: rabbitmq-sandbox2
  port: 5672
action:
  pass: rabbitmq-sandbox2`

For testing:
andres@MIS3749:~$ curl rabbit.apps.ocptest.domain.com:30552 -vvv
*   Trying 10.21.64.102:30552...
* TCP_NODELAY set
* connect to 10.xx.xx.xx2 port 30552 failed: Connection refused
* Failed to connect to rabbit.apps.ocptest.domain.com port 30552: Connection refused
* Closing connection 0

**Comment by brianehlert** [comment]
Your ports are not matching.  You did sort out that you 
You added additional ports to the service definition for rabbitmq - they all appear to be TCP ports, so I expect them to all be:

1. represented by a Listener in GlobalConfiguration
2. represented by a TransportServer
3. modify the ingress controller service to expose the port

5672, 15672, 5552, 15692 (maybe not this one if it is Prometheus) - these all need both a Listener and a TransportServer to represent them.

The Listener under GlobalConfiguration tells NGINX to listen for connections on this port.  The TransportServer then defines how to handle the traffic from that listener.  Modifying the Service of the ingress controller says which additional external ports to expose.

**Comment by andrescolodrero** [comment]
Hi,
i simpllify the service  to:
```
kind: Service
apiVersion: v1
metadata:
  name: my-service
  namespace: rabbitmq-system
spec:
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app.kubernetes.io/name: rabbitmq-sandbox2
```

and for simplicifty too, match the ports:
```
apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration 
metadata:
  name: nginx-configuration
  namespace: rabbitmq-system
spec: 
  listeners:
  - name: rabbitmq-tcp
    port: 5672
    protocol: TCP

```

and reconfigure the listener:

```
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: rabbitmq-listener
  namespace: rabbitmq-system
spec:
  host: rabbitmq.apps.ocptest.domain.com
  listener:
    name: rabbitmq-tcp
    protocol: TCP
upstreams:
- name: my-service
  service: my-service
  port: 5672
action:
  pass: my-service
```

still having same issue.
is there a way to check if the listener is running? or im missing something?
