### DISCUSSION TITLE
Helm repository source changes after v3.0.2 (v0.16.2) - the future for helm.nginx.com?

### DISCUSSION THREAD

**Discussion by Syntaf** [nginx/kubernetes-ingress#4217] [Q&A] [answered]
Hey all, first off love the work the team has done for this chart; nginx-ingress has been my go-to solutions for the last couple of years when spinning up a new project in my K8S cluster.

I looked into upgrading from chart version [0.17.1](https://artifacthub.io/packages/helm/nginx/nginx-ingress/0.17.1) to [0.18.0](https://artifacthub.io/packages/helm/nginx/nginx-ingress/0.18.0) today and noticed that my helm chart repository source is no longer listed anywhere in the docs:

```yaml
# Chart.yaml
# ...
dependencies:
  - name: nginx-ingress
    version: "0.17.1"
    repository: "https://helm.nginx.com/stable"
```

It looked like [0.16.2](https://artifacthub.io/packages/helm/nginx/nginx-ingress/0.16.2) was the last version to mention this repo source, version onwards are now using an [OCI registry](https://helm.sh/blog/storing-charts-in-oci/#helm)?

I don't see any release notes or deprecation warnings around the `https://helm.nginx.com/stable` repository source. Is it still safe to use this repo source for chart versions, and is there a migration guide to the OCI registry if this source will be going away soon?

Thanks for any info!
