### DISCUSSION TITLE
Many to one relationship for VirtualServerRoute and VirtualServer

### DISCUSSION THREAD

**Discussion by golpa** [nginx/kubernetes-ingress#4289] [Ideas]
**Is your feature request related to a problem? Please describe.**
We deploy multiple websites and have certain common sub paths across all of them. Currently we have to duplicate these sub paths for each site. 

For example we have:
http://site1/commonPath1
http://site1/commonPath2
http://site2/commonPath1
http://site2/commonPath2

Currently we we have to deploy 4 resource for the above setup (2 `VirtualServers` and 2 `VirtualServerRoutes`). This multiplies rather quickly if you have many sites and many common sub paths. 

The reason for this is that the `Host` field in a `VirtualServerRoute` has to match the `Host` field in a `VirtualServer`. 

**Describe the solution you'd like**
If possible, it would be nice to remove the restriction to require a `Host` field in a `VirtualServerRoute` allowing that route to be used in any VirtualServer that includes it. This would allow us to create routes for the common sub paths once and include them in every `VirtualServer` as necessary.

**Describe alternatives you've considered**
We tried to use wildcard domains but the restriction is the same. For example we tried to define the VirtualServer as `site.domain` and the VirtualServerRoute as `"*.domain"` but the ingress controller considers this an invalid configuration.

**Additional context**
Full sample setup we currently use:
```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: site1
spec:
  host: site1.domain
  upstreams:
    - name: site1App
      port: 80
      service: site1_app_service
  routes:
    - path: /
      proxy:
        upstream: site1App
    - path: /commonPath
      route: site1CommonPath
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: site1CommonPath
spec:
  host: site1.domain
  subroutes:
  - action:
      proxy:
        upstream: myCommonApp
    path: /commonPath
  upstreams:
  - name: myCommonApp
    port: 80
    service: my_common_app_service
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: site2
spec:
  host: site2.domain
  upstreams:
    - name: site2App
      port: 80
      service: site2_app_service
  routes:
    - path: /
      proxy:
        upstream: site2App
    - path: /commonPath
      route: site2CommonPath
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: site2CommonPath
spec:
  host: site2.domain
  subroutes:
  - action:
      proxy:
        upstream: myCommonApp
    path: /commonPath
  upstreams:
  - name: myCommonApp
    port: 80
    service: my_common_app_service
```

Instead of the above it would be nice to have the following setup where we declare the VirtualServerRoute once and use it for both VirtualServers

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: site1
spec:
  host: site1.domain
  upstreams:
    - name: site1App
      port: 80
      service: site1_app_service
  routes:
    - path: /
      proxy:
        upstream: site1App
    - path: /commonPath
      route: commonPath
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: site2
spec:
  host: site2.domain
  upstreams:
    - name: site2App
      port: 80
      service: site2_app_service
  routes:
    - path: /
      proxy:
        upstream: site2App
    - path: /commonPath
      route: commonPath
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: commonPath
spec:
  # host: site1.domain <-- alternative to removing would be to support "*.domain" to match to both VirtualServers
  subroutes:
  - action:
      proxy:
        upstream: myCommonApp
    path: /commonPath
  upstreams:
  - name: myCommonApp
    port: 80
    service: my_common_app_service
```
