### DISCUSSION TITLE
How to write access logs to /var/logs/nginx/access.log instead of stdout?

### DISCUSSION THREAD

**Discussion by noor-muradi** [nginx/kubernetes-ingress#4341] [Q&A] [answered]
How to make the Nginx ingress controller to write logs to log file instead of stdout?
I have deployed Nginx Ingress controller using the helm chart, I want to persist the logs using Persistent Volume so that I can use filebeat to push logs to Elastic Search for monitoring, the Nginx ingress by default output the logs to stdout, I have tried to make an entry to values.yaml but the logs are not written to /var/logs/access.log which is mounted to PVC and the hostPath which is configured in PVC has the permission RWX for UID "101" 
```
controller:
  config:
    entries:
      access-log: /var/log/nginx/access.log
```
