### DISCUSSION TITLE
Does the upstream support proxy pass a request to a long domain or to IP （not a service name）

### DISCUSSION THREAD

**Discussion by xuziheng1002** [nginx/kubernetes-ingress#4419] [Ideas]
upstreams:
  - name: tea
    service: tea-svc.example.com
    port: 80

do it works? like location.proxy_pass https://tea-svc.example.com/;
Alternatively, what configuration approach should I use to fulfill my requirements?

**Comment by github-actions** [comment]
Hi @xuziheng1002 thanks for reporting! 

 Be sure to check out the [docs](https://docs.nginx.com/nginx-ingress-controller) and the [Contributing Guidelines](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) while you wait for a human to take a look at this :slightly_smiling_face:

 Cheers!

**Comment by xuziheng1002** [comment]
I did a test, that is not work...
So if I want proxy request to the backend-server and the server is out of the Kubernetes how cloud I do?

**Comment by shaun-nx** [comment]
Hi @xuziheng1002
Can you provide full details of all of the YAML files you used when testing this?

**Comment by brianehlert** [comment]
Please provide your YAML.

Is this what you are looking for?  https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/custom-resources/externalname-services

**Comment by xuziheng1002** [comment]
> Please provide your YAML.
> 
> Is this what you are looking for? https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/custom-resources/externalname-services


following is my yaml:

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
 name: cafe
spec:
  gunzip: true
  host: cafe.example.com
  upstreams:
  - name: gateway-server
    service: gateway-server.example.com
    port: 80
  routes:
  - path: /api
     action:
       pass: gateway-server
  - path: /
    action:
      return:
        code: 200
        type: text/html
        body: '<!DOCTYPE html>
          <html>
          <body>hello world</body>
          <div id="root" style="height: 100%;"></div>
          </body>
          </html>'
```

My intention is to proxy_pass requests matching /api to the server gateway-server.example.com.

The problem is `service: gateway-server.example.com` is not valid for `VirtualServer`.
