### DISCUSSION TITLE
Acme Let's Encrypt challenge with VirtualServer + TLS redirect

### DISCUSSION THREAD

**Discussion by janisii** [nginx/kubernetes-ingress#4462] [General]
Hello!

How to configure VirtualServer with TLS redirect to be able to complete Acme Let's Encrypt challenge? Acme challenge request to /.well-know endpoint is automatically redirected to https (443) which result in `ERR_SSL_UNRECOGNIZED_NAME_ALERT` error and request cannot be full-filled.

Here is VS deployment:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: vs-test
  namespace: default
spec:
  host: vs-demo-test.example.com
  routes:
    - action:
        pass: test
      path: /
  tls:
    cert-manager:
      cluster-issuer: letsencrypt-prod
    redirect:
      enable: true
    secret: vs-demo-test.example.com-tls
  upstreams:
    - name: test
      port: 80
      service: test
```
