### DISCUSSION TITLE
How to setup multiple Ingresses for the same domain but with different ports

### DISCUSSION THREAD

**Discussion by hahahannes** [nginx/kubernetes-ingress#4480] [Q&A] [answered]
Hi,

I run an old version of the ingress controller and have two ingresses for the same host domain but they run with different ports (e.g. both ingresses run on foo.bar but on ports 8096 and 8097). As this will cause a host name collision, I cannot use it anymore. I thought to use the mergeable ingresses with a master and minion ingress but there the `nginx.org/listen-ports-ssl` is not allowed for minion ingresses. What is the supposed configuration for this usecase.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/listen-ports-ssl: "8096"
spec:
  tls:
    - hosts:
        - foo.bar
      secretName: tls
  rules:
    - host: foo.bar
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/listen-ports-ssl: "8097"
spec:
  tls:
    - hosts:
        - foo.bar
      secretName: tls
  rules:
    - host: foo.bar
```

**Comment by brianehlert** [comment]
According to the documentation `listen_ports` and` listen_ports_ssl` are arrays.  
https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/#listeners

I have not tried this, but you should be able to have one hosts entry and define both ports with a single annotation in the same Master Ingress (or single Ingress if not doing master/minion).

In the master / minion model, the master always holds the hostname.  And the minions are individual paths that get unique settings.

**Reply by hahahannes** [reply]
Thank you very much for your fast help! I did not realize that they are array types. I will try this.

**Reply by hahahannes** [reply]
Just wondering though how the routing is then done in the minion ingresses. For example if I want to route all requests at port `8097` to service `foo` and all requests at port `8096` to service `bar`. My whole setup is based on a single domain and different ports, so I cant use path based routing.

**Reply by hahahannes** [reply]
@brianehlert Do you maybe have an idea on how this routing usecase might be possible?

**Reply by brianehlert** [reply]
The only way that I am aware is to define an ingress for foo.company.com and a second ingress for bar.company.com

Or two VirtualServer resources, one for each hostname.

But not that you could do *.company.com and have foo. and bar. have different ports.  It goes back to a couple things.
One is how the ports connect to the laodbalancer and the other is how the server blocks are defined in the nginx.conf.

If you have a *.company.com, it will match foo or bar.  And now the order in which they are defined in the nginx.conf matters.  Because you need to define foo and bar explicitly and possibly use default_server for *.example.com or define the order of the server blocks.

http://nginx.org/en/docs/http/request_processing.html

Hmm...  Still thinking about this and if there is some possible way without creating a new default-server type annotation or setting to ensure the match processing happens properly, as the catch all needs to be the last in the list of server blocks.

**Reply by hahahannes** [reply]
@brianehlert Thanks again for your help! I think this kind of routing (one hostname, multiple ports) could be a valid usecase, though.

**Reply by brianehlert** [reply]
I am actually curious the reasoning behind segmenting traffic source by port (I am making an assumption that is what you are doing) within K8s.

**Reply by hahahannes** [reply]
There is no specific reason for this. We expose our main api via the standard http ports and expose some internal tools over other ports to circumvent path based routing over the main api. Because of other reasons, we only have one domain. Otherwise I would have just used subdomains.

**Reply by hahahannes** [reply]
And the ingress controller provided the setting for `nginx.org/listen-ports-ssl`, so we decided to use port routing

**Reply by hahahannes** [reply]
I think we will switch to path based routing using the master/minion ingresses

**Reply by brianehlert** [reply]
If you want to stay with the Ingress resource that is fine.
With our custom resources (VirtualServer) you can define custom ports as well.  That is a newer capability.

**Reply by hahahannes** [reply]
With VirtualServers, I would have to use one VirtualServer and multiple VirtualServerRoutes (because of the host name collisions). But can I set custom ports on VirtualServerRoutes?

**Reply by hahahannes** [reply]
I totally forgot that we already this conversation a year ago @brianehlert  (https://github.com/nginxinc/kubernetes-ingress/issues/3313). Back then, my hope was, that the host name collision check could be changed so that it actually checks for host name + port collisions . Maybe to change it here: https://github.com/nginxinc/kubernetes-ingress/blob/d78f57bed96f137c1c54217162182f8bdf4d5e74/internal/k8s/configuration.go#L1285

**Reply by hahahannes** [reply]
Ah, I see that the ingress ressources dont have the port specified :/ Might it be possible to make the host name collision check optional?

**Reply by brianehlert** [reply]
I see where you are going with the https://github.com/nginxinc/kubernetes-ingress/issues/3313 comment.
NGINX will always perform the hostname check it isn't necessarily something in the controller logic.
There is probably a way to do this, we just have to find it.

**Reply by hahahannes** [reply]
In case someone else stumbles across this. We switched to Istio. Here is an example replacement for an ingress 
```yml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway
spec:
  hosts:
    - '*'
  gateways:
    - gateway
  http:
    - match:
        - port: 1234
      route:
        - destination:
            host: foo-server
            port:
              number: 8080
```

**Reply by jasonwilliams14** [reply, marked as answer]
@hahahannes You can use snippets to add another port to the `virtualServer`. You can use something like the following:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  server-snippets: |
    listen 8081;
```
That will add 8081 to the `cafe.example.com` server block.

The full example:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  server-snippets: |
    listen 8081;
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    action:
      pass: tea
  - path: /coffee
    action:
      pass: coffee
```
Our `host` field also supports wildcards:

https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/

HTH
