### DISCUSSION TITLE
Adding nginx-prometheus-exporter as a sidecar in nginx-ingress helm chart.

### DISCUSSION THREAD

**Discussion by jcholowaty** [nginx/kubernetes-ingress#4495] [Q&A]
Hi! i'm using the NGINX Ingress Controller helm chart v0.18.0 in GKE and trying to add a sidecar the nginx-prometheus-exporter v0.11.0 but the that container fail.

```
nginxStatus:
    ## Enable the NGINX stub_status, or the NGINX Plus API.
    enable: true

    ## Set the port where the NGINX stub_status or the NGINX Plus API is exposed.
    port: 8080

    ## Add IPv4 IP/CIDR blocks to the allow list for NGINX stub_status or the NGINX Plus API. Separate multiple IP/CIDR by commas.
    allowCidrs: "127.0.0.1,::1"

prometheus:
  ## Expose NGINX or NGINX Plus metrics in the Prometheus format.
  create: true

  ## Configures the port to scrape the metrics.
  port: 9113

  ## Specifies the namespace/name of a Kubernetes TLS Secret which will be used to protect the Prometheus endpoint.
  secret: ""

  ## Configures the HTTP scheme used.
  scheme: http

extraContainers:
  - name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:0.11.0
    args:
      - '-nginx.scrape-uri=http://nginx-gke-argocd-stg-nginx-ingress-controller:9113/metrics'
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
    ports:
      - containerPort: 9113


kubectl get svc -n nginx-ingress
NAME                                            TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)                      AGE
nginx-gke-argocd-stg-nginx-ingress-controller   LoadBalancer   10.215.1.108   34.86.221.10   80:32348/TCP,443:31387/TCP   4h44m
```

In the args i configured the svc of the nginx-ingress deploy and in the first place the :8080/stub_status and 9113/metrics but nothing works.

How can I make the exporter work? Thanks a lot for your help!!
