### DISCUSSION TITLE
services with more than 1 ports issues

### DISCUSSION THREAD

**Discussion by Rockawear** [nginx/kubernetes-ingress#4624] [Q&A] [answered]
Hi,
Does VirtualServer & VirtualServerRoutes handle services with two ports or more? I'm seeing issues where I set two `upstream` with the same service name but a different port. It doesn't work it's complaining about duplicate upstream. The services is pointing at the same container pod. Any help is appreciated.

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: virtual-server
spec:
  host: virtual-server.example.com
  tls:
    secret: virtual-server-route-tls-grpc-secret
  routes:
  - path: "/helloworld.Greeter"
    route: virtual-server-route
  - path: "/backend1/test"
    route: virtual-server-route
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: virtual-server-route
spec:
  host: virtual-server.example.com
  upstreams:
  - name: backendgrpc
    service: backend
    port: 50051
    type: grpc
  - name: backendhttp
    service: backend
    port: 80
   type: http
  subroutes:
  - path: "/helloworld.Greeter"
    action:
      pass: backendgrpc
  - path: "/backend1/test"
    action:
      pass: backendhttp
```
