### DISCUSSION TITLE
Nginx Ingress Controller on GKE Autopilot with Google Cloud Anthos (Istio and Envoy under the hood)

### DISCUSSION THREAD

**Discussion by xcfw** [nginx/kubernetes-ingress#4818] [Q&A]
Hello everyone! I'm trying to configure nginx to work with istio's virtualservice to achieve **cookie-based canary deployment routing** and whenever I deploy manifests below I get 502 error in logs of ingress and nothing in istio-sidecar logs. My guess is that traffic from ingress is not sent via sidecar and therefore can't reach virtualservice.
I know that config is very specific, and still kindly asking for a help with figuring out what part of it is wrong and hopeful to get a direction where to search for a solution.

I use `nginx/nginx-ingress:3.3.2` ingress installed via helm and google's `gcr.io/gke-release/asm/proxyv2:1.16.7-asm.10` for the sidecar.

Here below my manifests:

<details>
  <summary>How deployment and Virtualservers are configured</summary>

## Main website helm rendered manifests:
```yaml
---
# Source: example/charts/web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/instance: example
    spec:
      serviceAccountName: example
      containers:
        - name: web
          image: ghcr.io/examplerepo/web:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: web-configmap
            - secretRef:
                name: web-secret
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /probe/startup
              port: 3000
            failureThreshold: 6
            periodSeconds: 45
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /probe/live
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 7
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 3000
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 2000m
              ephemeral-storage: 16Gi
              memory: 4Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 8Gi
              memory: 2Gi
---
# Source: example/charts/canaryWeb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-web
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/component: canary
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: example
      app.kubernetes.io/component: canary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/instance: example
        app.kubernetes.io/component: canary
        version: canary
    spec:
      serviceAccountName: example
      containers:
        - name: canary-web
          image: ghcr.io/examplerepo/web:v2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: canary-web-configmap
            - secretRef:
                name: canary-web-secret
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /probe/startup
              port: 3000
            failureThreshold: 6
            periodSeconds: 45
            timeoutSeconds: 15
          livenessProbe:
            httpGet:
              path: /probe/live
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 7
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 3000
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 2000m
              ephemeral-storage: 16Gi
              memory: 4Gi
            requests:
              cpu: 1000m
              ephemeral-storage: 8Gi
              memory: 2Gi
---
# Source: example/charts/web/templates/istionet.yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: web
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  host: web
  subsets:
    - name: main
      labels:
        version: main
      trafficPolicy:
        loadBalancer:
          consistentHash:
            httpCookie:
              name: userAffinity=main
              ttl: 3h
    - name: canary
      labels:
        version: canary
---
# Source: example/charts/web/templates/virtualserver.yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: web
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  host: www.example-website.com
  tls:
    redirect:
      enable: true
  upstreams:
    - name: web
      service: web
      port: 80
      use-cluster-ip: true
  routes:
    - path: ~ /settings
      location-snippets: |
        add_header        Content-Security-Policy  "" always;
        add_header        X-XSS-Protection         "1; mode=block" always;
        add_header        X-Content-Type-Options   "nosniff" always;
        add_header        Referrer-Policy          "strict-origin-when-cross-origin" always;
        add_header        X-Origin-Instance        "gke" always;
        proxy_hide_header X-Frame-Options;
      action:
        proxy:
          upstream: web
          requestHeaders:
            set:
            - name: Host
              value: web.staging.svc.cluster.local
    - path: /
      action:
        proxy:
          upstream: web
          requestHeaders:
            set:
            - name: Host
              value: web.staging.svc.cluster.local
  server-snippets:   |-
    sendfile                on;
    tcp_nopush              on;
    tcp_nodelay             on;
    types_hash_max_size     2048;
    types_hash_bucket_size  64;
  
    # Proxy tuning
    proxy_buffer_size       256k;
    proxy_buffers           4 512k;
    proxy_busy_buffers_size 512k;
    proxy_connect_timeout   180s;
    proxy_read_timeout      180s;
    proxy_send_timeout      180s;
  
    # SSL Tweaks
    resolver                1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
    resolver_timeout        2s;
    ssl_buffer_size         4k;
    ssl_protocols           TLSv1.3;
    ssl_session_cache       shared:SSL:10m;
    ssl_session_tickets     off;
    ssl_session_timeout     1d;
    # ssl_prefer_server_ciphers            off;
    # ssl_stapling                         on;
    # ssl_stapling_verify                  on;
  
    # Gzip compression tweaks
    gzip              on;
    gzip_buffers      16 8k;
    gzip_comp_level   9;
    gzip_http_version 1.1;
    gzip_proxied      any;
    gzip_types        text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss application/atom+xml image/svg+xml text/javascript;
    gzip_vary         on;
  
    # CSP and HTTP tweaks
    add_header        X-XSS-Protection         "1; mode=block" always;
    add_header        X-Content-Type-Options   "nosniff" always;
    add_header        X-Origin-Instance        "gke";
    add_header        Referrer-Policy          "strict-origin-when-cross-origin" always;
    # some other headers added

    # Top level rules

    location = / {
      proxy_pass https://www.example-landing.com/homepage;
      add_header X-Origin-Instance "gke-next-static";
    }

---
# Source: example/charts/web/templates/istionet.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  hosts:
    - web
  http:
    - match:
        - headers:
            Cookie:
              regex: .*userAffinity=main.*
      route:
        - destination:
            host: web
            subset: main
    - match:
        - headers:
            Cookie:
              regex: .*userAffinity=canary.*
      route:
        - destination:
            host: web
            subset: canary
    - route:
        - destination:
            host: web
            subset: main
          weight: 99
        - destination:
            host: web
            subset: canary
          weight: 1
          headers:
            response:
              add:
                Set-Cookie: userAffinity=canary; Max-Age=3600000

---
```

</details>

<details>
  <summary>How nginx deployment is configured</summary>

## NGINX with helm resulting yamls:

```yaml
---
# Source: nginx-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-ingress-controller
  namespace: ingress
  labels:
    helm.sh/chart: nginx-ingress-1.0.2
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/version: "3.3.2"
    app.kubernetes.io/managed-by: Helm
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 28.48.48.40
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: ingress
---
# Source: nginx-ingress/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-ingress-controller
  namespace: ingress
  labels:
    helm.sh/chart: nginx-ingress-1.0.2
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/version: "3.3.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress
      app.kubernetes.io/instance: ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-ingress
        app.kubernetes.io/instance: ingress
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/scheme: "http"
        sidecar.istio.io/inject: "true"
        traffic.sidecar.istio.io/excludeInboundPorts: 80,443
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.42.42.0/22
        traffic.sidecar.istio.io/includeInboundPorts: ""
    spec:
      serviceAccountName: ingress-nginx-ingress
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - image: nginx/nginx-ingress:3.3.2
        name: nginx-ingress
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: prometheus
          containerPort: 9113
        - name: readiness-port
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
          initialDelaySeconds: 0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsUser: 101 #nginx
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus=false
          - -nginx-reload-timeout=60000
          - -enable-app-protect=false
          - -enable-app-protect-dos=false
          - -nginx-configmaps=$(POD_NAMESPACE)/ingress-nginx-ingress
          - -ingress-class=nginx
          - -health-status=true
          - -health-status-uri=/nginx-health
          - -nginx-debug=false
          - -v=1
          - -nginx-status=true
          - -nginx-status-port=8080
          - -nginx-status-allow-cidrs=127.0.0.1
          - -report-ingress-status
          - -external-service=ingress-nginx-ingress-controller
          - -enable-leader-election=true
          - -leader-election-lock-name=ingress-nginx-ingress-leader-election
          - -wildcard-tls-secret=ingress/example-website-wildcard-tls
          - -enable-prometheus-metrics=true
          - -prometheus-metrics-listen-port=9113
          - -prometheus-tls-secret=
          - -enable-service-insight=false
          - -service-insight-listen-port=9114
          - -service-insight-tls-secret=
          - -enable-custom-resources=true
          - -enable-snippets=true
          - -include-year=false
          - -disable-ipv6=false
          - -enable-tls-passthrough=false

          - -enable-preview-policies=false
          - -enable-cert-manager=false
          - -enable-oidc=false
          - -enable-external-dns=false
          - -ready-status=true
          - -ready-status-port=8081
          - -enable-latency-metrics=true
---
# Source: nginx-ingress/templates/controller-ingress-class.yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
    helm.sh/chart: nginx-ingress-1.0.2
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/version: "3.3.2"
    app.kubernetes.io/managed-by: Helm
spec:
  controller: nginx.org/ingress-controller
---
```

</details>

**Comment by jasonwilliams14** [comment]
@xcfw Hello there.

Have you injected the istio sidecar into the NGINX Ingress controller pod?
The 502 looks like that NGINX Ingress is unable to communicate with the istio sidecar and in my testing, I get this when the istio sidecars are not able to communicate to each other.

can you provdie the output of a describe on the NGINX ingress controller pod?
are you able to provide the output of the `nginx.conf` that is generated so we can review the .conf ?

Thanks

**Reply by xcfw** [reply]
Yeah, I got sidecars injected:

![image](https://github.com/nginxinc/kubernetes-ingress/assets/1721246/244da0d0-e44c-436f-a41b-ba91c30eddb4)

```bash
> kubectl get pods -n ingress
NAME                                                READY   STATUS    RESTARTS   AGE
ingress-nginx-ingress-controller-7c5664-ntm    2/2     Running   0          5m30s
ingress-nginx-ingress-controller-795664-qqv    2/2     Running   0          4m54s
```
Here's raw nginx configs:
<details>
  <summary>nginx.conf</summary>

```bash
> k exec -it -n nginx deploy/nginx-ingress-controller -- cat /etc/nginx/nginx.conf
```

```nginx

worker_processes  auto;
daemon off;

error_log  stderr notice;
pid        /var/lib/nginx/nginx.pid;

events {
    worker_connections  2048;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    map $upstream_trailer_grpc_status $grpc_status {
        default $upstream_trailer_grpc_status;
        '' $sent_http_grpc_status;
    }

    access_log  /dev/stdout  main;

    log_format response_time '{"upstreamAddress":"$upstream_addr", "upstreamResponseTime":"$upstream_response_time", "proxyHost":"$proxy_host", "upstreamStatus": "$upstream_status"}';
    access_log syslog:server=unix:/var/lib/nginx/nginx-syslog.sock,nohostname,tag=nginx response_time;


    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout 65s;
    keepalive_requests 100;

    #gzip  on;

    server_names_hash_max_size 1024;
    server_names_hash_bucket_size 256;

    variables_hash_bucket_size 256;
    variables_hash_max_size 1024;

    map $request_uri $request_uri_no_args {
        "~^(?P<path>[^?]*)(\?.*)?$" $path;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    map $http_upgrade $vs_connection_header {
        default upgrade;
        ''      $default_connection_header;

    }
    
    server {
        # required to support the Websocket protocol in VirtualServer/VirtualServerRoutes
        set $default_connection_header "";
        set $resource_type "";
        set $resource_name "";

        set $resource_namespace "";
        set $service "";

        listen 80 default_server;
        listen [::]:80 default_server;

        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;

        ssl_reject_handshake on;
        
        server_name _;
        server_tokens "on";

        location /nginx-health {
            default_type text/plain;
            return 200 "healthy\n";
        }

        location / {
            return 404;
        }
    }
    # stub_status
    server {
        listen 8080;
        listen [::]:8080;


        allow 127.0.0.1;

        deny all;

        location /stub_status {
            stub_status;
        }
    }
    server {
        listen unix:/var/lib/nginx/nginx-status.sock;
        access_log off;



        location /stub_status {
            stub_status;
        }
    }

    include /etc/nginx/config-version.conf;
    include /etc/nginx/conf.d/*.conf;

    server {
        listen unix:/var/lib/nginx/nginx-502-server.sock;
        access_log off;



        return 502;
    }

    server {
        listen unix:/var/lib/nginx/nginx-418-server.sock;
        access_log off;



        return 418;

    }

}

stream {

    log_format  stream-main  '$remote_addr [$time_local] '
                      '$protocol $status $bytes_sent $bytes_received '
                      '$session_time "$ssl_preread_server_name"';


    access_log  /dev/stdout  stream-main;



    map_hash_max_size 2048;
    map_hash_bucket_size 256;




    include /etc/nginx/stream-conf.d/*.conf;
}
```

</details>

<details>
  <summary>vhost.conf</summary>

```bash
kubectl exec -it -n nginx deploy/nginx-ingress-controller -- cat /etc/nginx/conf.d/vs_testing_web.conf
```

```nginx

upstream vs_testing_web_web {
    zone vs_testing_web_web 256k;

    random two least_conn;

    server unix:/var/lib/nginx/nginx-502-server.sock max_fails=1 fail_timeout=10s max_conns=0;
    
}

server {
        
    listen 80;
    listen [::]:80;
        

    server_name www.example-website.com;

    set $resource_type "virtualserver";
    set $resource_name "web";
    set $resource_namespace "testing";
        
    listen 443 ssl;
    listen [::]:443 ssl;
        
    ssl_certificate /etc/secrets/wildsecret;
    ssl_certificate_key /etc/secrets/wildsecret;

    if ($scheme = 'http') {
        return 301 https://$host$request_uri;
    }

    server_tokens "on";

    sendfile                on;
    tcp_nopush              on;
    tcp_nodelay             on;
    types_hash_max_size     2048;
    types_hash_bucket_size  64;
    
    # Proxy tuning
    proxy_buffer_size       256k;
    proxy_buffers           4 512k;
    proxy_busy_buffers_size 512k;
    proxy_connect_timeout   180s;
    proxy_read_timeout      180s;
    proxy_send_timeout      180s;
    
    # SSL Tweaks
    resolver                1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
    resolver_timeout        2s;
    ssl_buffer_size         4k;
    ssl_protocols           TLSv1.3;
    ssl_session_cache       shared:SSL:10m;
    ssl_session_tickets     off;
    ssl_session_timeout     1d;
    # ssl_prefer_server_ciphers            off;
    # ssl_stapling                         on;
    # ssl_stapling_verify                  on;
    
    # Gzip compression tweaks
    gzip              on;
    gzip_buffers      16 8k;
    gzip_comp_level   9;
    gzip_http_version 1.1;
    gzip_proxied      any;
    gzip_types        text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss application/atom+xml image/svg+xml text/javascript;
    gzip_vary         on;
    
    # CSP and HTTP tweaks
    add_header        X-XSS-Protection         "1; mode=block" always;
    add_header        X-Content-Type-Options   "nosniff" always;
    add_header        X-Origin-Instance        "gke";
    add_header        Referrer-Policy          "strict-origin-when-cross-origin" always;
    
    # Some other headers added
    # Top level rules
    
    location = / {
      proxy_pass https://www.example-langing.com/home;

      add_header X-Origin-Instance "gke-landing-static";
    }
    
    # Plugin landing pages rules
    
    location ~ /(.*)-website-app(.*)$ {
      proxy_pass https://www.example-langing.com/en/stuff/$1$2;
      add_header X-Origin-Instance "gke-langing-static";
    }
    
    location ~ "/settings" {
        set $service "web";
        
        add_header        Content-Security-Policy  "" always;
        add_header        X-XSS-Protection         "1; mode=block" always;
        add_header        X-Content-Type-Options   "nosniff" always;
        add_header        Referrer-Policy          "strict-origin-when-cross-origin" always;
        add_header        X-Origin-Instance        "gke" always;
        proxy_hide_header X-Frame-Options;
            
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
        client_max_body_size 200m;

        proxy_buffering on;
            
        proxy_http_version 1.1;
        set $default_connection_header close;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $vs_connection_header;
        proxy_pass_request_headers on;
            
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host "web.testing.svc.cluster.local";
            
        proxy_pass http://vs_testing_web_web;
            
        proxy_next_upstream error timeout;
        proxy_next_upstream_timeout 0s;
        proxy_next_upstream_tries 0;
        
    }
    
    location / {

        set $service "web";
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;

        proxy_send_timeout 60s;
        client_max_body_size 200m;

        proxy_buffering on;
            
        proxy_http_version 1.1;
        set $default_connection_header close;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $vs_connection_header;
        proxy_pass_request_headers on;
            
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host "web.testing.svc.cluster.local";

        proxy_pass http://vs_testing_web_web;
            
        proxy_next_upstream error timeout;
        proxy_next_upstream_timeout 0s;
        proxy_next_upstream_tries 0;
        
    }
    
}
```

</details>

**Reply by jasonwilliams14** [reply]
@xcfw Thx. 
Looking at your config, I do not see any `servers` in your `upstream` output:

```
upstream vs_testing_web_web {
    zone vs_testing_web_web 256k;

    random two least_conn;

    server unix:/var/lib/nginx/nginx-502-server.sock max_fails=1 fail_timeout=10s max_conns=0;
    
}
```
You should see the cluster-ip for the web service in your deployment and specified in your `virtualServer`

```
  upstreams:
    - name: web
      service: web
      port: 80
      use-cluster-ip: true
```

Can you list the service? (in the appropriate namespace)
```
kubectl get svc 
```

**Reply by xcfw** [reply]
yes, I removed web service, as when I turn it on, istio.virtualservice's percentage of weights don't work at all, i.e. it seems that nginx is just using service to communicate in oppose to using virtualservice. Adding service back solve the 502 issue, but then about 50% of requests go to canary when there should be 1%. my understanding was that we should see virtualservice in the upstream section.

**Reply by brianehlert** [reply]
NGINX Ingress Controller (by default) sends traffic direct to upstream service pod IPs.  Bypassing the service IP endpoint.
Istio requires that NIC send traffic to the service IP so that Istio can capture that and own the routing to the backend pods.

The special setting "use-cluster-ip" is necessary to enable NIC for this special use case.
https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#upstream:~:text=No-,use%2Dcluster%2Dip,-Enables%20using%20the

**Reply by xcfw** [reply]
use-cluster-ip is enabled, it's in config on the first message, I just thought that virtualservice should be used intead of service

**Reply by xcfw** [reply]
I added service back, and traffic now goes not through virtualservice, but service:

```bash
> k get svc -n testing
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
counter      ClusterIP   10.44.11.227     <none>        80/TCP    49d
web          ClusterIP   10.44.19.178     <none>        80/TCP    12h
```
Despite `use-cluster-ip` being enabled and action.proxy being configured as in tutorial (https://docs.nginx.com/nginx-ingress-controller/tutorials/nginx-ingress-istio/):

```yaml
  upstreams:
    - name: web
      service: web
      port: 80
      use-cluster-ip: true
```

```yaml
      action:
        proxy:
          upstream: web
          requestHeaders:
            set:
            - name: Host
              value: web.staging.svc.cluster.local
```
when k8s service is enabled with this:

```yaml
# Source: example/charts/web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: powr
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: http-web
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: powr
  type: ClusterIP
```

I get bad results with curl:

```bash
> echo ":::canary:::"; for i in $(seq 1 10); do sleep 1s;
curl -b "userAffinity=canary"  https://www.example-website.com/version.html; echo "\n";
done; echo "\n\n:::main:::"; for i in $(seq 1 10); do sleep 1s;
curl -b "userAffinity=main"  https://www.example-website.com/version.html; echo "\n";
done;

:::canary:::
v1
v2
v1
v2
v2
v2
v1
v1
v1
v2

:::main:::
v1
v2
v2
v1
v1
v2
v1
v2
v2
v1
```
And because this behaviour is similar if I delete istio, and use just k8s service without service mesh at all, and because logs show that traffic is not passed through envoy with k8s service enabled I thought about ways to force nginx to use envoy and send traffic via istio's virtualservice:

<details>
  <summary>click here</summary>

```yaml
# Source: example/charts/web/templates/istionet.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web
  labels:
    helm.sh/chart: web-0.1.0
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  hosts:
    - web
  http:
    - match:
        - headers:
            Cookie:
              regex: .*userAffinity=main.*
      route:
        - destination:
            host: web
            subset: main
    - match:
        - headers:
            Cookie:
              regex: .*userAffinity=canary.*
      route:
        - destination:
            host: web
            subset: canary
    - route:
        - destination:
            host: web
            subset: main
          weight: 99
        - destination:
            host: web
            subset: canary
          weight: 1
          headers:
            response:
              add:
                Set-Cookie: userAffinity=canary; Max-Age=3600000
```
</details>
