### DISCUSSION TITLE
Cert manager not working after nginx migration

### DISCUSSION THREAD

**Discussion by spoorthyredi2** [nginx/kubernetes-ingress#5158] [Q&A]
Recently we have migrated from using Community maintained Kubernetes Controller to NIC (3.3.0)  and Nginx (1.25.2)
Post that the Auto renewal of TLS Certificates is failing .  
The Http-01 challenges are failing with 404 or 403  errors.

`Waiting for HTTP-01 challenge propagation: wrong status code '403', expected '200', Processing: true, Presented: true`

During the time of renewal a new ingress for acme gets created  but looks like its not reachable from nginx and hence the request gets routed instead to cert-manager instead of the acme solver pod . 

Cert manager Webhook logs - 
I1205 06:12:31.009927       1 dynamic_source.go:266] cert-manager/webhook "msg"="Updated cert-manager webhook TLS certificate" "DNSNames"=["cert-manager-webhook","cert-manager-webhook.cert-manager","cert-manager-webhook.cert-manager.svc"]
I1208 11:21:07.746462       1 logs.go:59] http: TLS handshake error from 10.0.1.4:51434: EOF

As per most users, such issues occur because the challenge request cannot route to acme solver pod. How can I rule out nginx issue here ?

**Comment by spoorthyredi2** [comment]
Noticed my current ClusterIssuer has
```
spec:
  acme:
    email: <fghjkl>
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
```
and when I try to update it to
`ingressClassName: nginx`
I get ,  unknown field "spec.acme.solvers[0].http01.ingress.ingressClassName"    


What is the right way to give class name in ClusterIssuer?

 (edited)

**Reply by jasonwilliams14** [reply]
@spoorthyredi2 what version of certmanager are you running?
I believe in version 1.12 theey added `ingressClassName`:

https://cert-manager.io/docs/configuration/acme/http01/

```
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
```
