### DISCUSSION TITLE
nginx behind ingress - 404 Not Found

### DISCUSSION THREAD

**Discussion by n00bsi** [nginx/kubernetes-ingress#5288] [General]
Hello,
I do my first steps so I am a NOOB! Sorry about that !

```
# kubectl get pods -o wide -A
NAMESPACE       NAME                                       READY   STATUS      RESTARTS      AGE   IP                NODE     NOMINATED NODE   READINESS GATES
default         nginx-deployment-94bd5979-g46wg            1/1     Running     0             22h   10.1.33.131       k8sn27   <none>           <none>
default         nginx-deployment-94bd5979-h7p7j            1/1     Running     0             22h   10.1.192.67       k8sn26   <none>           <none>
default         nginx-deployment-94bd5979-sr457            1/1     Running     0             22h   10.1.223.67       k8sn25   <none>           <none>
ingress-nginx   ingress-nginx-admission-create-pm8gz       0/1     Completed   0             22h   10.1.223.65       k8sn25   <none>           <none>
ingress-nginx   ingress-nginx-admission-patch-wwhd7        0/1     Completed   1             22h   10.1.192.65       k8sn26   <none>           <none>
ingress-nginx   ingress-nginx-controller-5458dd5f6-4hrrq   1/1     Running     0             22h   10.1.33.129       k8sn27   <none>           <none>
......
webdemo         nginx-deployment-94bd5979-jgtfb            1/1     Running     0             22h   10.1.223.66       k8sn25   <none>           <none>
webdemo         nginx-deployment-94bd5979-knnf4            1/1     Running     0             22h   10.1.33.130       k8sn27   <none>           <none>
webdemo         nginx-deployment-94bd5979-p2zx9            1/1     Running     0             22h   10.1.192.66       k8sn26   <none>           <none>



# kubectl get svc -A
NAMESPACE       NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default         kubernetes                           ClusterIP   10.96.0.1       <none>        443/TCP                      8d
ingress-nginx   ingress-nginx-controller             NodePort    10.99.244.151   <none>        80:31801/TCP,443:32504/TCP   22h
ingress-nginx   ingress-nginx-controller-admission   ClusterIP   10.99.125.252   <none>        443/TCP                      22h
kube-system     kube-dns                             ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP       8d


```

#  kubectl describe svc -n ingress-nginx
```
Name:                     ingress-nginx-controller
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/component=controller
                          app.kubernetes.io/instance=ingress-nginx
                          app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/part-of=ingress-nginx
                          app.kubernetes.io/version=1.10.0
Annotations:              <none>
Selector:                 app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.99.244.151
IPs:                      10.99.244.151
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  31801/TCP
Endpoints:                10.1.33.129:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  32504/TCP
Endpoints:                10.1.33.129:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>


Name:              ingress-nginx-controller-admission
Namespace:         ingress-nginx
Labels:            app.kubernetes.io/component=controller
                   app.kubernetes.io/instance=ingress-nginx
                   app.kubernetes.io/name=ingress-nginx
                   app.kubernetes.io/part-of=ingress-nginx
                   app.kubernetes.io/version=1.10.0
Annotations:       <none>
Selector:          app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.99.125.252
IPs:               10.99.125.252
Port:              https-webhook  443/TCP
TargetPort:        webhook/TCP
Endpoints:         10.1.33.129:8443
Session Affinity:  None
Events:            <none>

```

Worker Nodes IPs: 192.168.122.225 - 227 ( k8sn25, k8sn26, k8sn27 )

```
# kubectl get nodes -o wide
NAME     STATUS   ROLES           AGE   VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE                              KERNEL-VERSION                 CONTAINER-RUNTIME
k8sn22   Ready    control-plane   8d    v1.29.3   192.168.122.222   <none>        AlmaLinux 9.3 (Shamrock Pampas Cat)   5.14.0-362.18.1.el9_3.x86_64   docker://25.0.5
k8sn23   Ready    control-plane   8d    v1.29.3   192.168.122.223   <none>        AlmaLinux 9.3 (Shamrock Pampas Cat)   5.14.0-362.18.1.el9_3.x86_64   docker://25.0.5
k8sn24   Ready    control-plane   8d    v1.29.3   192.168.122.224   <none>        AlmaLinux 9.3 (Shamrock Pampas Cat)   5.14.0-362.18.1.el9_3.x86_64   docker://25.0.5
k8sn25   Ready    worker          8d    v1.29.3   192.168.122.225   <none>        AlmaLinux 9.3 (Shamrock Pampas Cat)   5.14.0-362.18.1.el9_3.x86_64   docker://25.0.5
k8sn26   Ready    worker          8d    v1.29.3   192.168.122.226   <none>        AlmaLinux 9.3 (Shamrock Pampas Cat)   5.14.0-362.18.1.el9_3.x86_64   docker://25.0.5
k8sn27   Ready    worker          8d    v1.29.3   192.168.122.227   <none>        AlmaLinux 9.3 (Shamrock Pampas Cat)   5.14.0-362.18.1.el9_3.x86_64   docker://25.0.5

```

```
# curl --noproxy '*' 192.168.122.226:31801
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

# curl --noproxy '*' 10.1.223.66:80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

```

```

# cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - containerPort: 80




# cat service.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - containerPort: 80



# cat ingress.yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: webdemo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: ImplementationSpecific        
        backend:
          service:
            name: test
            port:
              number: 80

```

created by doing this:

```
kubectl create ns webdemo

kubectl apply -f service.yaml

kubectl apply -f deployment.yaml -n webdemo

kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/baremetal/deploy.yaml


kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission

kubectl apply -f ingress.yaml

```

**What did I wrong ?**

I accpected to can access the ngnix by:

```
curl --noproxy '*' 192.168.122.227:31801
curl --noproxy '*' 192.168.122.226:31801
curl --noproxy '*' 192.168.122.225:31801

```

but got:

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

```
# curl --noproxy '*' 192.168.122.227:31801/testpath
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

Only when do:   curl --noproxy '*' 10.1.223.66:80 ( pod IP ) when use the worker Nodes IP there is nothing in the logs

got a entry in the logs

kubectl logs -n webdemo -l app=nginx -f
`
10.1.219.0 - - [21/Mar/2024:12:58:00 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.76.1" "-"
`
