### DISCUSSION TITLE
Enter drain mode when a pod is terminating and sticky-sessions are enabled

### DISCUSSION THREAD

**Discussion by dcowden** [nginx/kubernetes-ingress#5962] [Ideas]
We have a legacy application ( tomcat/java), which needs sticky sessions. When we deploy new versions of our applications, we need to stop sending new connections to a server, while sending bound sessions to the old server. Please note: this is not referring to in-flight requests, we're needing the active tomcat sessions to expire, which normally takes a few hours.

This is possible using nginx drain command. This will send bound connections to the old server, but send new ones elsewhere. But in kubernetes, calling a command on the ingress controller is not part of the deployment flow. To do it with current tools, we would need to add a preStop hook to our application. In that hook, we'd need to access the ingress controller, and ask it to drain with an api call. We'd rather not introduce the ability for applications to call apis on the ingress controller.

When kubernetes terminates a pod, it enters the TERMINATING status.  In nearly all cases, when sticky sessions are enabled, the desired functionality is probably to put the associated pod into drain mode. Is this possible with the nginx-plus ingress controller?

We currently use the [kubernetes-maintained nginx ingress controller](https://github.com/kubernetes/ingress-nginx/). This feature would make it worth the money to use nginx-plus

**Comment by pleshakov** [comment]
@dcowden Maybe the following approach can work you? 

If you want to drain particular pods, you change the corresponding Ingress resource by adding an annotation that specifies which pods to drain using a label query. For example:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.com/drain: "version=0.1"
spec:
  rules:
  - host: "cafe.example.com"
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
```
In this case, the Ingress controller will drain all the pods corresponding to the tea-svc with the label `version=0.1`. This will allow you to specify which pods to drain during an application upgrade. 

Please not that this is not available, but we can add it.
