### DISCUSSION TITLE
Implementing Rate Limit based on Nginx policy How to implement rate limiting in a virtual server

### DISCUSSION THREAD

**Discussion by datavisorrunziyang** [nginx/kubernetes-ingress#6078] [Q&A] [answered]
For a single nginx controller, the rate limit can be implemented accurately, but for multiple pods, the limit rate will double with the number of pods.

**Comment by j1m-ryan** [comment, marked as answer]
Hi @datavisorrunziyang , this feature was recently implemented. You can use the `scale` paramater on the rateLimit policy from version `3.6.0`. You can see the docs on this [here](https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/#ratelimit)

Eg like this
```yaml
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-policy
spec:
  rateLimit:
    rate: 1r/s
    key: ${binary_remote_addr}
    zoneSize: 10M
    scale: true
```
