### DISCUSSION TITLE
Is it possible to use same host path for 2 different services exposed to 2 different port?

### DISCUSSION THREAD

**Discussion by RitikaLaddha** [nginx/kubernetes-ingress#6103] [Q&A]
here, I am trying to use same host path for 2 different services exposed at 2 different port. Will below ingress work?

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myingress
  namespace: pg-connector
  labels:
    app.kubernetes.io/instance: myhelm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: myhelm
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: virtual-server-0.1.0
  annotations:
    kubernetes.io/tls-acme: 'true'
    meta.helm.sh/release-name: myhelm
    meta.helm.sh/release-namespace: pg-connector
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/use-regex: 'true'
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hostname
      secretName: secretname
  rules:
    - host: hostname
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service1
                port:
                  number: 5432
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  number: 8080
status:
  loadBalancer:
    ingress:
      - ip: 
```
