### DISCUSSION TITLE
ingress endpoint queuing latency - how to optimize it

### DISCUSSION THREAD

**Discussion by veldpworld** [nginx/kubernetes-ingress#6157] [General]
<img width="706" alt="image" src="https://github.com/user-attachments/assets/b6210712-2a7c-47e2-9ec2-a696d44ad633">

there is an queuing latency and it says 360ms ,  we use http2 in the application.  is there any recommended configmap parameter for the ingress controller for this endpoint?   if they running application locally there is not much queuing thorugh ingress connectivity(private lb) it has this queuing latency.  

can you please recommd the ingress controller config map for using http2 ?

**Comment by j1m-ryan** [comment]
> can you please recommd the ingress controller config map for using http2 ?

Setting the key is `http2` is sufficient.
It can be set like this
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  http2: "true"
```

Can you give us some extra environment information to help us investigate this?

- Version of the Ingress Controller - release version or a specific commit
- Version of Kubernetes
- Kubernetes platform (e.g. Mini-kube or GCP)
- Using NGINX or NGINX Plus

**Reply by j1m-ryan** [reply]
Hi @veldpworld, for tuning NIC for http2, you can set these params in the config map
```yaml
  access-log-off: "True"
  http2: "True"
  keepalive-requests: "10000000"
  worker-connections: "100000"
  worker-processes: "16"
  worker-rlimit-nofile: "102400
```
and the following snippets and config options to your VirtualServers
```yaml
spec:
  host: nginx.traefik.ben-tests.com
  routes:
  - action:
      pass: whoami
    location-snippets: "proxy_request_buffering off;      \n"
    path: /
  server-snippets: |
    http2_max_concurrent_streams 512;
  tls:
    secret: my-tls
  upstreams:
  - buffering: false
    client-max-body-size: 9999m
    max-fails: 0
    name: whoami
    port: 8000
    service: whoami
```
