### DISCUSSION TITLE
Cert Manager for TransportServer

### DISCUSSION THREAD

**Discussion by j1m-ryan** [nginx/kubernetes-ingress#6390] [Ideas]
Cert Manager is very useful for VirtualServer (and Ingress). It would be useful to have this extended to TransportServer
```yaml
apiVersion: k8s.nginx.org/v1
kind: TransportServer
metadata:
  name: dns-tcp
spec:
  listener:
    name: dns-tcp
    protocol: TCP
  tls:
    secret: cafe-secret
    cert-manager:
       cluster-issuer: prod-issuer
  upstreams:
  - name: dns-app
    service: dns-service
    port: 5353
  action:
    pass: dns-app
```
