### DISCUSSION TITLE
Incorporate the new NGINX Plus OIDC module into Policies object

### DISCUSSION THREAD

**Discussion by pdabelf5** [nginx/kubernetes-ingress#7956] [Ideas]
Add support into NGINX Ingress Controller [Policies](https://github.com/nginx/kubernetes-ingress/blob/main/config/crd/bases/k8s.nginx.org_policies.yaml) to include the new NGINX Plus [ngx_http_oidc_module](https://nginx.org/en/docs/http/ngx_http_oidc_module.html) for OIDC flows.  

There are several ways to achieve this:
- replace the existing [OIDC Policy](https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/#oidc) which is based on the [NGINX NJS OIDC reference implementation](https://github.com/nginxinc/nginx-openid-connect) with the [ngx_http_oidc_module](https://nginx.org/en/docs/http/ngx_http_oidc_module.html) and drop unsupported options until they become available in the module.  This will likely mean a new version of the `Policy` CRD, for example,`v2alpha`.  The original OIDC Policy will still be available in the `v1` CRD.
- add a new `Policy` that drives configuration of the `ngx_http_oidc_module` module alongside the existing `Policy`.

The existing OIDC Policy spec is
```
spec:
  oidc:
    clientID: nginx-plus
    clientSecret: oidc-secret
    authEndpoint: https://idp.example.com/openid-connect/auth
    authExtraArgs: []
    tokenEndpoint: https://idp.example.com/openid-connect/token
    jwksURI: https://idp.example.com/openid-connect/certs
    endSessionEndpoint: https://idp.example.com/openid-connect/logout
    scope: oidc
    redirectURI: /_codexch
    postLogoutRedirectURI: /
    zoneSyncLeeway: 200
    accessTokenEnable: true
    pkceEnable: false
```

Thoughts welcome.
