### ISSUE TITLE
Rate Limiting based on a claim

### ISSUE THREAD

**Issue by shaun-nx** [nginx/kubernetes-ingress#6565]
# Overview
As a user of NGINX Ingress Controller, I would like to identify a user based on a provided JWT and apply different rate limiting rules based on attributes of that user so that, for example, a premium user can perform more request per second than a non premium users.

## Requirements
- Allow the number of requests per second enforced by a rate limiting policy to change based on attributes of a JWT
- Initial Implementation of this feature will **not** be included in `kind: Ingress`. This **may** come later

### Development

- [ ]  Unit tests are written to cover functionality delivered in the story.
- [ ]  Make sure that the unit test passes before creating a pull request.
- [ ]  Make sure that the test coverage stays optimal.
- [ ]  Run `make lint` locally before creating a PR.

### Testing

- [ ]  Automated tests are written as part of the story.
- [ ]  Run “make lint-python“ from root
- [ ]  Acceptance criteria are met.
- [ ]  Stories are demonstrated to the team.
- [ ]  Product Manager accepts the story as done.
- [ ]  If a feature requires changes/extensions of the Helm chart, those shall be done as part of the story.

### Release Notes & Documentation

- [ ]  PR is labeled appropriately so they display in GitHub release notes.
- [ ]  Create/update documentation related to the user story.
- [ ]  Create/update the example in our codebase when applicable.

```[tasklist]
### POC Tasks
- [ ] SPIKE - Investigate enabling RateLimiting based on JWT
```

```[tasklist]
### Implementation Tasks
```

**Comment by pdabelf5** [comment]
The current design is to extend the `rateLimit` Policy to add a `jwtCondition` block to allow the setting of custom claims and defining a default limit.  For example: 
```yaml
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: gold-rate-limit-policy
spec:
  rateLimit:
    rate: 10r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    jwtCondition:
      claim: consumer_group tier
      value: Gold
      default: false
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: silver-rate-limit-policy
spec:
  rateLimit:
    rate: 5r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    jwtCondition:
      claim: consumer_group tier
      value: Silver
      default: false
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: bronze-rate-limit-policy
spec:
  rateLimit:
    rate: 1r/s
    key: ${jwt_claim_sub}
    zoneSize: 10M
    jwtCondition:
      claim: consumer_group tier
      value: Bronze
      default: true
---
```
