### ISSUE TITLE
Configure NIC pods with `zone_sync` enabled without TLS support

### ISSUE THREAD

**Issue by AlexFenlon** [nginx/kubernetes-ingress#7219]
Is your feature request related to a problem? Please describe.
As an engineer, I want zone_sync to a feature for NIC to allow state sharing.
Prereq: https://github.com/nginx/kubernetes-ingress/issues/7218

### Acceptance Criteria

- [x] No TLS for this issue
- [x] `zone-sync` data read from the `nginx-config` (ConfigMap)
- [x] input data validated
- [x] generate headless service (no user input, read namespace name only)

headless service example:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-headless
  namespace: nginx-ingress
spec:
  clusterIP: None
  selector:
    app: nginx-ingress
```

~~-- lookup selector:app value from NIC deployment obj - it will be the name for app:selector in the headless service (we match NIC deployment with the headless service)~~
~~-- on NIC startup -> create headless service (K8s API call) - (?) Do we start NIC if this call fails?~~
~~-- learn where to put the code (`controller.go` ?) for managing config map zone-sync changes - during runtime~~
~~-- we need to remove headless service when user removes zone-sync (or set to `false`) from the nginx-ingress config map~~
~~-- we need to add headless service when user enables zone-sync (or set to `true`) in the nginx-ingress config map~~

- [x] templates generate correct zone-sync config
- [x] Manifest implementation
- [x] Update Documentation
   - ready once this pr goes in
