### ISSUE TITLE
[Bug]: OIDC Adds ":" to redirect URI even though no port is specified in URL.

### ISSUE THREAD

**Issue by benshalev849** [nginx/kubernetes-ingress#7278]
### Version

3.7.0

### What Kubernetes platforms are you running on?

Openshift

### Steps to reproduce

We are deploying the NGINX as usual and using the "NGINX OIDC" policy.
When using it and diving into some of the code we saw that the redirect URI automatically adds a `:` in the redirect URI which can break it and doesn't make much sense. (In our env it's a problem since specifying ports is not allowed in redirect_uris.)

As seen in the following file on line 6-9: [internal/configs/oidc/oidc_common.conf](https://github.com/nginx/kubernetes-ingress/blob/05861e2376df5a69b46814ec64c762999ecec0d8/internal/configs/oidc/oidc_common.conf#L6)

We saw that there is mapping of the redirect URI based on `$server_port` and `$http_x_forwarded_port`.

When using HTTPS there is no port "specified" thus if our domain is: `my-oidc-tests.com` it will result in the following redirect URI: `https://my-oidc-tests.com:/_codexch` which breaks our SSO provider.

We think a better solution is adding the `:` and a port only when it actually exists or even have an option to toggle it on or off.

I opened under a bug because we are not sure if this is intended behaviour (the default adding of `:` into the URI or not.)

Thank you :)

**Comment by haywoodsh** [comment]
Hi @benshalev849, in NGINX Ingress Controller, the redirect URI is restricted to be the same host as the virtual server.  Can you share the OIDC policy and virtual server yaml you were deploying?

**Comment by benshalev849** [comment]
It is the same host, the main problem is it adding the `:` to the end which seems weird when no port specificed.
So in the below example the redirect URI will be:

`https://ben.oidc.com:/nginx-oidc (with ':')`

`https://ben.oidc.com/nginx-oidc`

The oidc policy:

```
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-policy
spec:
  oidc: 
    clientID: test-ben
    authEndpoint: <sso_endpoint>/protocol/openid-connect/auth
    tokenEndpoint: <sso_endpoint>/protocol/openid-connect/token
    jwksURI: : <sso_endpoint>/protocol/openid-connect/certs
    endSessionEndpoint: : <sso_endpoint>/protocol/openid-connect/logout
    scope: openid+profile+email
    accessTokenEnable: true
    redirectURI: /nginx-oidc
```

The VS:

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: my-oidc-vs
spec:
  host: ben.oidc.com
  policies:
    -name: oidc-policy
  tls: {}
  upstreams:
    - name: backend
       service: simple-http-backend
       port: 8080
  routes:
    - path: /
       action:
         pass: backend
```

**Comment by haywoodsh** [comment]
We recently introduced the integration test for OIDC in our pipeline to ensure it functions correctly in our standard environment. https://github.com/nginx/kubernetes-ingress/blob/main/tests/suite/test_oidc.py
Therefore, I would assume the issue you are experiencing is specific to your environment, and it would be difficult for us to accommodate every possible deployment scenario. That said, would you mind sharing more information about your environment, such as which identity platform you are using?

**Comment by benshalev849** [comment]
@haywoodsh 

I have specified in the issue the lines of code where the mapping adds the `:` by default, it's here: [internal/configs/oidc/oidc_common.conf](https://github.com/nginx/kubernetes-ingress/blob/05861e2376df5a69b46814ec64c762999ecec0d8/internal/configs/oidc/oidc_common.conf#L6)

```
map $http_x_forwarded_port $redirect_base {
    ""      $proto://$host:$server_port;
    default $proto://$host:$http_x_forwarded_port;
}
```

This means that if no server port or http_x_forwared port is specified it will still add the ":" hardcoded hence resulting the the bad redirect URI containing a `:` in it even though no port is specified.

**Comment by jjngx** [comment]
@benshalev849 could you please let us know what IDP and config you use?

**Comment by LiorVayness** [comment]
I'm a colleague of @benshalev849 so i will continue the conversation with you while he is gone :)
As an IDP we have Keycloak in our environment. 
About the configs, we use the ones from ben's response:

> The oidc policy:
> 
> ```
> apiVersion: k8s.nginx.org/v1
> kind: Policy
> metadata:
>   name: oidc-policy
> spec:
>   oidc: 
>     clientID: test-ben
>     authEndpoint: <sso_endpoint>/protocol/openid-connect/auth
>     tokenEndpoint: <sso_endpoint>/protocol/openid-connect/token
>     jwksURI: : <sso_endpoint>/protocol/openid-connect/certs
>     endSessionEndpoint: : <sso_endpoint>/protocol/openid-connect/logout
>     scope: openid+profile+email
>     accessTokenEnable: true
>     redirectURI: /nginx-oidc
> ```
> 
> The VS:
> 
> ```
> apiVersion: k8s.nginx.org/v1
> kind: VirtualServer
> metadata:
>   name: my-oidc-vs
> spec:
>   host: ben.oidc.com
>   policies:
>     -name: oidc-policy
>   tls: {}
>   upstreams:
>     - name: backend
>        service: simple-http-backend
>        port: 8080
>   routes:
>     - path: /
>        action:
>          pass: backend
> ```

The configmap looks like so:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  resolver-addresses: dns-default.openshift-dns.svc.cluster.local
  resolver-valid: 5s
  access-log-off: 'False'
  http2: 'True'
  stream-snippets: |
    server {
        listen 12345;
        listen [::]:12345;
        zone_sync;
        zone_sync_server nginx-ingress-headless.nginx-ingress.svc.cluster.local:12345 resolve;
    }
```

Also when we tried to reach the site when the redirect wasn't yet configured we saw that the redirectURI received in the url request what like so: `redirect_uri=https://my-oidc-tests.com:/_codexch`
if you need more config files let me know :)

**Comment by vepatel** [comment]
Hi @benshalev849 would you mind telling us what's the redirect URI set in keycloak console and confirm is it ends with `/_codexch`

**Comment by vepatel** [comment]
thanks @benshalev849 , can you try changing resolver address to `kube-dns.kube-system.svc.cluster.local` and see if something changes?

**Comment by vepatel** [comment]
@LiorVayness 

> (In our env it's a problem since specifying ports is not allowed in redirect_uris.)
Is this the case with keycloak console as well?  
see https://docs.nginx.com/nginx/deployment-guides/single-sign-on/keycloak/#configuring-keycloak for vanilla Nginx Plus with OIDC guidance.

**Comment by vepatel** [comment]
@benshalev849 the code you pointed out is actually [a reference implementation of nginx with oidc](https://github.com/nginxinc/nginx-openid-connect/blob/main/openid_connect_configuration.conf#L87-L89) which we use so not something we can modify and also I'm unable to repro the issue with keycloak unfortunately

**Comment by AlexFenlon** [comment]
Hi @benshalev849,

as mentioned, the given redirect URI result is 

> &redirect_uri=https://webapp.example.com:443/_codexch

**Comment by benshalev849** [comment]
@AlexFenlon 

Did you specify a port 443 when sending the request?

In our case we access `https://webapp.example.com` with no specified port and the result is an empty port: `https://webapp.example.com:/_codexch`

In addition, in cases where the port does not actually directly typed in the URL, https+http why is it in the redirect URI?

Is there a way to "remove" this behaviour?

**Comment by haywoodsh** [comment]
The port is not customizable because `redirectURI` only accepts a relative path.

**Comment by vepatel** [comment]
hey @benshalev849 can you please try removing `redirectURI: /nginx-oidc` from the [policy](https://github.com/nginx/kubernetes-ingress/issues/7278#issuecomment-2687265795)  and check if the `Validate redirect URIs` field in keycloak idp is set to `https://ben.oidc.com:443/_codexch`

**Comment by benshalev849** [comment]
> hey [@benshalev849](https://github.com/benshalev849) can you please try removing `redirectURI: /nginx-oidc` from the [policy](https://github.com/nginx/kubernetes-ingress/issues/7278#issuecomment-2687265795) and check if the `Validate redirect URIs` field in keycloak idp is set to `https://ben.oidc.com:443/_codexch`

Hello, i have tested it previously with both and the result was the same as with a redirectURI variable.
We are on version 3.7.0.

**Comment by route443** [comment]
@benshalev849 ,

May I ask you to provide the very first response from your server that’s protected by OIDC?
That is, if you go to `https://my-oidc-tests.com`, nginx should return a redirect to the AS for authentication, something like:

```
GET https://n1.example.com/ HTTP/1.1
Host: n1.example.com
...

HTTP/1.1 302 Moved Temporarily
Server: nginx/x.xx
...
WWW-Authenticate: Bearer realm=""
Set-Cookie: auth_redir=/; Path=/; SameSite=lax;
auth_nonce=...; Path=/; SameSite=lax;
Location: https://keycloak.loc/auth/realms/master/protocol/openid-connect/auth?response_type=code&scope=openid+profile+email+offline_access&client_id=nginx&redirect_uri=https://n1.example.com:443/_codexch&nonce=...&state=0
```

Thanks!

**Comment by LiorVayness** [comment]
@route443 

The message does seem to have the location without the port. This is the first nginx redirect message returned from the server:
```
Request URL: https://lior.oidc.com/
Request Method: GET
Status Code: 302 Found
Location: https://private.sso.com/auth/realms/prod/protocol/openid-connect/auth?response_type=code&scope=openid&client_id=nginx-oidc&redirect_uri=https://lior.oidc.com:/_codexch&nonce=<token>&state=0
Server: nginx/1.25.5
WWW-Authenticate: Bearer realm=""
Set-Cookie: auth_redir=%2F; Path=/; SameSite=lax; HttpOnly; Secure;
```

**Comment by vepatel** [comment]
hi @LiorVayness would you be able to provide us with some info from https://github.com/nginx/kubernetes-ingress/issues/7278#issuecomment-2919085513? and importantly the redirectURI in idp

**Comment by vepatel** [comment]
Also if you can add below log-format in your nginx configmap:

```
data:
  log-format: '"redirect_base: $redirect_base" "x_forwarded_port: $http_x_forwarded_port" "server_port: $server_port" "proto: $proto"'
```

and check the value of server_port and x_forwarded_port in NIC pod logs, should be something like:
`"redirect_base: https://myidp.example.com:443" "x_forwarded_port: -" "server_port: 443" "proto: https"`

**Comment by LiorVayness** [comment]
@vepatel 
screenshotting the IDP is kind of an issue because we work inside an on-prem environment. about the tls configuration, we use it as empty since we use the wildcard certificate as our cert, i added the redirect to the configuration so now the virtual-server looks like this:

The new VS:
 ```
 apiVersion: k8s.nginx.org/v1
 kind: VirtualServer
 metadata:
   name: my-oidc-vs
 spec:
   host: lior.oidc.com
   policies:
     -name: oidc-policy
   tls:
     redirect:
       enable: true
   upstreams:
     - name: backend
        service: simple-http-backend
        port: 8080
   routes:
     - path: /
        action:
          pass: backend
 ```

The oidc policy:
 ```
 apiVersion: k8s.nginx.org/v1
 kind: Policy
 metadata:
   name: oidc-policy
 spec:
   oidc: 
     clientID: nginx-oidc
     authEndpoint: <sso_endpoint>/protocol/openid-connect/auth
     tokenEndpoint: <sso_endpoint>/protocol/openid-connect/token
     jwksURI: : <sso_endpoint>/protocol/openid-connect/certs
     endSessionEndpoint: : <sso_endpoint>/protocol/openid-connect/logout
     scope: openid+profile+email
     accessTokenEnable: true
 ```

The configured redirectURI in the idp is: `https://lior.oidc.com:/_codexch`
