### ISSUE TITLE
[Bug]: Cannot run a second  ingresscontroller with a second different SA

### ISSUE THREAD

**Issue by NICK0TIN** [nginx/kubernetes-ingress#7700]
### Version

4.0.1

### What Kubernetes platforms are you running on?

Openshift

### Steps to reproduce

Via the OpenShift operatorhub I try to create 2 or more NginxIngress object that will trigger the helm chart to deploy the Nginx controller.

 The 2nd controller I try to deploy fails, because the first SA "nginx-ingress" is created and managed by the first Helm chart.

I read that this can be configured by setting the values file:
```
controller:
  serviceAccount:
    ## Autogenerated if not set or set to "".
    name: nginx-ingress
```
However no matter the name given, the SA will always be created as nginx-ingress.

I wonder this could be due to:
charts/nginx-ingress/templates/controller-serviceaccount.yaml

where the SA is only create in this condition:

`{{- if .Values.rbac.create }}`

Should this not be .Values.controller.rbac.create as shown in the sample values file?

Steps to reproduce:

Create any NginxIngress on OpenShift and give a different name than nginx-ingress.

```
controller:
  serviceAccount:
    ## Autogenerated if not set or set to "".
    name: nginx-ingress-test
```

![Image](https://github.com/user-attachments/assets/5c83fc5d-c210-469b-91b7-6b2ac8933813)
![Image](https://github.com/user-attachments/assets/e3019341-bce6-4cba-83ad-20ef06e6fc66)
