### ISSUE TITLE
POC - Rate Limit with API Key

### ISSUE THREAD

**Issue by shaun-nx** [nginx/kubernetes-ingress#7704]
### POC Scope

- [x] Determine `spec` of rate limit policy
- [x] Should a apiKey policy be required? (context A JWT policy was not required for the JWT RL), yes an APIKey Policy is required to provide the client name for the apikey.
- [x] What would be the key for the rate limit zone? Any valid `apikey_` variable could be used.  A new variable to identify the  client name will be created, for example, `apikey_client_name`.
- [x] Create design document

Example setup with snippets

```yaml
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  http-snippets: |
    map $apikey_auth_client_name_nginx_ingress_cafe_api_key_policy $GroupName {
    default Group1;
    "~^(.*-gold)" Group1;
    "~^(.*-plat)" Group2;
    }

    map $GroupName $Zone1Var {
        default "";
        Group1 gold;
    }

    map $GroupName $Zone2Var {
        default "";
        Group2 plat;
    }

    limit_req_zone $Zone1Var zone=Zone1:10m rate=5r/m;
    limit_req_zone $Zone2Var zone=Zone2:10m rate=15r/s;
  host: cafe.example.com
  tls:
    secret: cafe-secret
  policies:
  - name: api-key-policy
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /coffee
    location-snippets: |
            limit_req zone=Zone1;
            limit_req zone=Zone2;
    action:
      pass: coffee
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: api-key-client-secret
type: nginx.org/apikey
data:
    client1-gold: Z29sZA== # gold
    client2-plat: cGxhdA== # plat
    client1: cGFzc3dvcmQ= # password
```

**Comment by pdabelf5** [comment]
Example using exact match (REJECTED DESIGN):
```
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-premium
spec:
  rateLimit:
    rate: 100r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        match: "client1"
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-basic
spec:
  rateLimit:
    rate: 10r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        match: "client2"
      default: true
---
```

Example using regex:
```
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-premium
spec:
  rateLimit:
    rate: 100r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        match: "~^.*-premium$"
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-basic
spec:
  rateLimit:
    rate: 10r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        match: "~^.*-basic$"
      default: true
---
```

**Comment by pdabelf5** [comment]
Example using list (REJECTED DESIGN):

```
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-premium
spec:
  rateLimit:
    rate: 100r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        clients:
          - client-1
          - client-2
          - client-3
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-basic
spec:
  rateLimit:
    rate: 10r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      apiKey:
        clients:
          - client-a
          - client-b
          - client-c
      default: true
---
```

**Comment by benshalev849** [comment]
Hello, as discussed in the PoC zoom call i am adding an example of how we managed to rate limit based on method+api key tiering.

The VS Let's as control which method/any other NGINX variable we limit, and if we want to pass all others. (in this example i am using $request_method) but i believe it will work with any other variable.

```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  http-snippets: |
    map $apikey_auth_client_name_nginx_ingress_cafe_api_key_policy $GroupName {
    default $request_method-gold;
    "~^(.*-gold)" $request_method-gold;
    "~^(.*-plat)" $request_method-plat;
    }

# Example of limiting only POST for zone 1
    map $GroupName $Zone1Var {
        default "";
        POST-gold gold;
  
    }

# Example of limiting for zone 2 DELETE+POST:

    map $GroupName $Zone2Var {
        default "";
        POST-plat plat;
        DELETE-plat plat;
    }

    limit_req_zone $Zone1Var zone=Zone1:10m rate=5r/m;
    limit_req_zone $Zone2Var zone=Zone2:10m rate=15r/s;
  host: cafe.example.com
  tls:
    secret: cafe-secret
  policies:
  - name: api-key-policy
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /coffee
    location-snippets: |
            limit_req zone=Zone1;
            limit_req zone=Zone2;
    action:
      pass: coffee
```

**Comment by pdabelf5** [comment]
More generic approach to ratelimiting based on a variable (APPROVED DESIGN)
```
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-premium
spec:
  rateLimit:
    rate: 1r/s
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      variable:
        match: "~^.*-premium$"
        name: $apikey_client_name
      default: true
---
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-apikey-basic
spec:
  rateLimit:
    rate: 1r/m
    key: ${apikey_client_name}
    zoneSize: 10M
    condition:
      variable:
        match: "~^.*-basic$"
        name: $apikey_client_name
      default: true
```

`variable` can match any nginx variable, not just related to apikey. 

Current implementation means you cannot have multiple tiered policies using the same conditions, so cannot re-use the same tiered policies within the same VS host.

**Comment by pdabelf5** [comment]
Add policies to VS/VSR matches (REJECTED DESIGN):
```
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.example.com
  tls:
    secret: cafe-secret
  upstreams:
  - name: coffee
    service: coffee-svc
    port: 80
  policies:
    - name: api-key-policy
  routes:
    path: /coffee
    matches:
    - conditions:
      - variable: $apikey_client_name
        value: premium
      policies:
        - name: rate-limit-apikey-premium
      action:
        pass: coffee
    policies:
      - name: rate-limit-apikey-basic
    action:
      pass: coffee
```

Design is too complicated
