### ISSUE TITLE
Extend Otel support for VirtualServer, VirtualServerRoute & Ingress

### ISSUE THREAD

**Issue by pdabelf5** [nginx/kubernetes-ingress#7791]
- [ ] Allow users to turn on Otel support at the server/location level of the NGINX config
  - [ ] Allow users to turn on Otel support at the VirtualServer level
  - [ ] Allow users to turn on Otel support at the VirtualServerRoute level
  - [ ] Allow users to turn on Otel support at the Ingress level
- [ ] Allow users to configure a additional directives for the Otel Exporter (See ConfigMap example).
- [ ] Add pytests for full OTEL deployment

ConfigMap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  otel-exporter-endpoint: "[(http|https)://]host:port" # Done # Required
  otel-exporter-trusted-certificate: "path/to/certificate" # Phase2 Secret # Optional
  otel-exporter-header-name: "name" # Done # Optional
  otel-exporter-header-value: "value" # Done  # Optional
  otel-exporter-interval: "time" # Phase2 # Optional
  otel-exporter-batch-size: "number" # Phase2 # Optional
  otel-exporter-batch-count: "number" # Phase2 # Optional
  otel-service-name: "unknown_service:nginx" # Done  # Optional
  otel-resource-attr-name: "name" # Phase2 # Optional
  otel-resource-attr-value: "value" # Phase2 # Optional
  otel-trace-in-http: "false" # Done  # Optional
```
