### ISSUE TITLE
OTEL Support

### ISSUE THREAD

**Issue by pdabelf5** [nginx/kubernetes-ingress#7792]
ConfigMap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  otel-exporter-endpoint: "[(http|https)://]host:port" # Done # Required
  otel-exporter-trusted-certificate: "path/to/certificate" # Phase2 Secret # Optional
  otel-exporter-header-name: "name" # Done # Optional
  otel-exporter-header-value: "value" # Done  # Optional
  otel-exporter-interval: "time" # Phase2 # Optional
  otel-exporter-batch-size: "number" # Phase2 # Optional
  otel-exporter-batch-count: "number" # Phase2 # Optional
  otel-service-name: "unknown_service:nginx" # Done  # Optional
  otel-resource-attr-name: "name" # Phase2 # Optional
  otel-resource-attr-value: "value" # Phase2 # Optional
  otel-trace-in-http: "false" # Done  # Optional
```

Example NGINX config
```
load_module modules/ngx_otel_module.so;

http {
    otel_exporter {
		endpoint https://otel-example.nginx.com:4317/;
	
		header X-API-Token "my-token-value";
	}
	otel_service_name "nginx";
	otel_resource_attr "abc" "123";
	otel_trace on;

	server {
		otel_trace off;


		location /abc {
		}

		location /xyz {
			otel_trace on;
			otel_trace_context extract;
		}

		location /123 {
			otel_trace on;
			otel_trace_context ignore;
		}
	}
}
```
